//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{

    /// <summary>
    /// <lang>
    ///   <zh-CN>公告展示用户控件的 Designer 字段容器；字段由 ASCX 服务器控件生成。</zh-CN>
    ///   <en>Designer field container for the announcements display user control; fields are generated from ASCX server controls.</en>
    /// </lang>
    /// </summary>
    public partial class Announcements
    {

        /// <summary><lang><zh-CN>显示公告模块标题的共享标题组件。</zh-CN><en>Shared title component that displays the announcements-module title.</en></lang></summary>
        protected global::ASPNET.StarterKit.Portal.DesktopModuleTitle Title1;

        /// <summary><lang><zh-CN>绑定公告条目的 DataList。</zh-CN><en>DataList bound to announcement entries.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DataList myDataList;
    }
}
