<%@ Control Language="c#" Inherits="ASPNET.StarterKit.Portal.Discussion" CodeBehind="Discussion.ascx.cs" AutoEventWireup="True" %>
<%@ Import Namespace="ASPNET.StarterKit.Portal" %>
<%--
<lang>
  <zh-CN>标记层直接调用讨论模块 code-behind 中的格式化和编码 helper，因此显式导入门户命名空间。</zh-CN>
  <en>The markup calls formatting and encoding helpers from the discussion module code-behind, so the portal namespace is imported explicitly.</en>
</lang>
--%>
<%@ Register TagPrefix="ASPNETPortal" TagName="Title" Src="~/DesktopModuleTitle.ascx" %>
<%--
<lang>
  <zh-CN>标题栏控件继续承载旧模块的编辑入口和权限可见性逻辑，避免讨论列表标记层重复实现模块标题区域。</zh-CN>
  <en>The title control continues to own the legacy module edit entry and visibility behavior, avoiding duplicate title-bar logic in the discussion list markup.</en>
</lang>
--%>

<%--
<lang>
  <zh-CN>讨论模块通过标题栏控件提供“新增主题”入口；是否可见由模块编辑权限和标题控件自身逻辑决定。</zh-CN>
  <en>The discussion module exposes the "add new thread" entry through the title control; visibility is decided by module edit permissions and the title control itself.</en>
</lang>
--%>
<ASPNETPortal:title id="Title1" runat="server" EditTarget="_new" EditUrl="~/DesktopModules/DiscussDetails.aspx" EditText="Add New Thread"></ASPNETPortal:title>

<%--
<lang>
  <zh-CN>讨论列表仍使用 DataList 和原展开/折叠命令模型，只把输出改为主题化线程列表，以保留旧回发行为和现有 code-behind 事件绑定。</zh-CN>
  <en>The discussion list keeps DataList plus the original expand/collapse command model while rendering a themed thread list, preserving legacy postback behavior and existing code-behind event bindings.</en>
</lang>
--%>
<asp:datalist id="TopLevelList" CssClass="portal-discussion-list" RepeatLayout="Flow" OnItemCommand="TopLevelList_OnItemCommand" runat="server" DataKeyField="Parent">
    <ItemTemplate>
        <div class="portal-discussion-row">
            <%--
            <lang>
              <zh-CN>P8.2 用文字状态按钮替代旧 plus/node GIF；命令名仍由 code-behind 计算，以保留原有展开行为。</zh-CN>
              <en>P8.2 replaced the old plus/node GIF with a textual state button; the command name is still computed by code-behind to preserve the original expand behavior.</en>
            </lang>
            --%>
            <asp:LinkButton id="btnSelect"
                            CssClass='<%# NodeToggleCssClass((int) DataBinder.Eval(Container.DataItem, "ChildCount")) %>'
                            Text='<%# NodeToggleText((int) DataBinder.Eval(Container.DataItem, "ChildCount")) %>'
                            Enabled='<%# HasChildMessages((int) DataBinder.Eval(Container.DataItem, "ChildCount")) %>'
                            ToolTip="Expand this thread"
                            CommandName='<%# NodeCommandName((int) DataBinder.Eval(Container.DataItem, "ChildCount")) %>'
                            runat="server" />
            <span class="portal-discussion-main">
                <%--
                <lang>
                  <zh-CN>主题文本先经 code-behind 编码 helper 处理，链接地址由站内详情页格式化方法生成。</zh-CN>
                  <en>The thread title is passed through the code-behind encoding helper, and the link URL is generated by the in-site detail-page formatter.</en>
                </lang>
                --%>
                <asp:hyperlink CssClass="portal-discussion-title" Text='<%# EncodeDisplayText(DataBinder.Eval(Container.DataItem, "Title")) %>' NavigateUrl='<%# FormatUrl((int) DataBinder.Eval(Container.DataItem, "ItemID")) %>' Target="_blank" runat="server" ID="Hyperlink1" />
                <span class="portal-discussion-meta">
                    from <%# EncodeDisplayText(DataBinder.Eval(Container.DataItem, "CreatedByUser")) %>
                    , posted <%# DataBinder.Eval(Container.DataItem, "CreatedDate", "{0:g}") %>
                </span>
            </span>
        </div>
    </ItemTemplate>
    
    <SelectedItemTemplate>
        <div class="portal-discussion-row portal-discussion-row-selected">
            <%--
            <lang>
              <zh-CN>P8.2 用文字状态按钮替代旧 minus GIF；折叠仍走原 `collapse` 命令，降低旧回发路径变化。</zh-CN>
              <en>P8.2 replaced the old minus GIF with a textual state button; collapse still uses the original `collapse` command to keep the legacy postback path stable.</en>
            </lang>
            --%>
            <asp:LinkButton id="btnCollapse" CssClass="CommandButton portal-discussion-toggle portal-secondary-action portal-discussion-toggle-selected"
                Text="Collapse" ToolTip="Collapse this thread" runat="server" CommandName="collapse" />
            <span class="portal-discussion-main">
                <%--
                <lang>
                  <zh-CN>选中主题与普通主题使用相同编码和站内链接策略，只在外层 CSS 类中体现选中状态。</zh-CN>
                  <en>The selected thread uses the same encoding and in-site link policy as normal rows; selection is expressed only through the outer CSS class.</en>
                </lang>
                --%>
                <asp:hyperlink CssClass="portal-discussion-title" Text='<%# EncodeDisplayText(DataBinder.Eval(Container.DataItem, "Title")) %>' NavigateUrl='<%# FormatUrl((int) DataBinder.Eval(Container.DataItem, "ItemID")) %>' Target="_blank" runat="server" ID="Hyperlink2" />
                <span class="portal-discussion-meta">
                    from <%# EncodeDisplayText(DataBinder.Eval(Container.DataItem, "CreatedByUser")) %>
                    , posted <%# DataBinder.Eval(Container.DataItem, "CreatedDate", "{0:g}") %>
                </span>
            </span>
        </div>

        <%--
        <lang>
          <zh-CN>子级讨论列表按当前主题的 DisplayOrder 查询回复，继续由 code-behind 控制缩进、日期格式和详情页链接。</zh-CN>
          <en>The child discussion list queries replies by the selected thread's DisplayOrder, while indentation, date formatting, and detail links remain controlled by code-behind.</en>
        </lang>
        --%>
        <asp:DataList ID="DetailList" CssClass="portal-discussion-children" RepeatLayout="Flow" DataSource='<%# GetThreadMessages((string) DataBinder.Eval(Container.DataItem, "DisplayOrder")) %>' runat="server">
            <ItemTemplate>
                <div class="portal-discussion-row portal-discussion-reply">
                    <%--
                    <lang>
                      <zh-CN>缩进 HTML 由 code-behind 按 DisplayOrder 生成，并限制为当前主题树的展示结构。</zh-CN>
                      <en>Indentation HTML is generated by code-behind from DisplayOrder and is limited to the current thread tree presentation.</en>
                    </lang>
                    --%>
                    <%# GetIndentHtml(Eval("DisplayOrder")) %>
                    <span class="portal-discussion-main">
                        <%--
                        <lang>
                          <zh-CN>回复标题同样通过编码 helper 输出，避免旧讨论内容直接进入页面文本节点。</zh-CN>
                          <en>Reply titles are also emitted through the encoding helper so legacy discussion content does not enter page text nodes directly.</en>
                        </lang>
                        --%>
                        <asp:HyperLink
                            CssClass="portal-discussion-title"
                            Text='<%# EncodeDisplayText(Eval("Title")) %>'
                            NavigateUrl='<%# FormatUrl((int)Eval("ItemID")) %>'
                            Target="_blank"
                            runat="server" />
                        <span class="portal-discussion-meta">
                            from <%# EncodeDisplayText(Eval("CreatedByUser")) %>
                            , posted <%# FormatDate(Eval("CreatedDate")) %>
                        </span>
                    </span>
                </div>
            </ItemTemplate>
        </asp:DataList>
    </SelectedItemTemplate>
</asp:datalist>
