//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class Document
    {

        /// <summary><lang><zh-CN>显示文档模块标题的共享标题组件。</zh-CN><en>Shared title component that displays the document-module title.</en></lang></summary>
        protected global::ASPNET.StarterKit.Portal.DesktopModuleTitle Title1;

        /// <summary><lang><zh-CN>绑定文档条目集合的 Repeater。</zh-CN><en>Repeater bound to the document-entry collection.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater myDataGrid;
    }
}
