//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class EditEvents
    {

        /// <summary><lang><zh-CN>活动标题输入框。</zh-CN><en>Event-title input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox TitleField;

        /// <summary><lang><zh-CN>活动描述输入框。</zh-CN><en>Event-description input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox DescriptionField;

        /// <summary><lang><zh-CN>活动地点和时间输入框。</zh-CN><en>Event location-and-time input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox WhereWhenField;

        /// <summary><lang><zh-CN>活动过期日期输入框。</zh-CN><en>Event-expiration date input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox ExpireField;

        /// <summary><lang><zh-CN>活动过期日期必填校验器。</zh-CN><en>Required-field validator for the event expiration date.</en></lang></summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredExpireDate;

        /// <summary><lang><zh-CN>活动过期日期格式或范围校验器。</zh-CN><en>Validator for the event expiration-date format or range.</en></lang></summary>
        protected global::System.Web.UI.WebControls.CompareValidator VerifyExpireDate;

        /// <summary><lang><zh-CN>显示活动字段校验结果的消息标签。</zh-CN><en>Message label for event-field validation results.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ValidationMessage;

        /// <summary><lang><zh-CN>提交活动编辑内容的命令按钮。</zh-CN><en>Command button that submits event edits.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton updateButton;

        /// <summary><lang><zh-CN>取消活动编辑的命令按钮。</zh-CN><en>Command button that cancels event editing.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton cancelButton;

        /// <summary><lang><zh-CN>删除当前活动的命令按钮。</zh-CN><en>Command button that deletes the current event.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton deleteButton;

        /// <summary><lang><zh-CN>显示活动创建者的只读标签。</zh-CN><en>Read-only label that displays the event creator.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label CreatedBy;

        /// <summary><lang><zh-CN>显示活动创建时间的只读标签。</zh-CN><en>Read-only label that displays the event creation time.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label CreatedDate;
    }
}
