//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class EditHtml
    {

        /// <summary><lang><zh-CN>显示桌面 HTML 内容字段标签。</zh-CN><en>Displays the label for the desktop HTML-content field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label DesktopTextLabel;

        /// <summary><lang><zh-CN>接收桌面 HTML 内容的输入框。</zh-CN><en>Input for desktop HTML content.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox DesktopText;

        /// <summary><lang><zh-CN>显示移动摘要字段标签。</zh-CN><en>Displays the label for the mobile-summary field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MobileSummaryLabel;

        /// <summary><lang><zh-CN>接收移动摘要内容的输入框。</zh-CN><en>Input for mobile summary content.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox MobileSummary;

        /// <summary><lang><zh-CN>显示移动详细内容字段标签。</zh-CN><en>Displays the label for the mobile-details field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MobileDetailsLabel;

        /// <summary><lang><zh-CN>接收移动详细 HTML 内容的输入框。</zh-CN><en>Input for mobile detailed HTML content.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox MobileDetails;

        /// <summary><lang><zh-CN>提交 HTML 内容更新的受控按钮。</zh-CN><en>Controlled button that submits the HTML-content update.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton updateButton;

        /// <summary><lang><zh-CN>取消当前 HTML 内容编辑的按钮。</zh-CN><en>Button that cancels the current HTML-content edit.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton cancelButton;
    }
}
