//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class EditImage
    {
        /// <summary><lang><zh-CN>显示图片来源字段标签。</zh-CN><en>Displays the image-source field label.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label SrcLabel;

        /// <summary><lang><zh-CN>图片来源 URL 输入框。</zh-CN><en>Input for the image-source URL.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox Src;

        /// <summary><lang><zh-CN>承载图片预览的面板。</zh-CN><en>Panel that contains the image preview.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel ImagePreviewPanel;

        /// <summary><lang><zh-CN>显示规范化图片地址预览的图片控件。</zh-CN><en>Image control that displays the normalized image URL preview.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Image ImagePreview;

        /// <summary><lang><zh-CN>显示图片宽度字段标签。</zh-CN><en>Displays the image-width field label.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label WidthLabel;

        /// <summary><lang><zh-CN>图片宽度输入框。</zh-CN><en>Input for the image width.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox Width;

        /// <summary><lang><zh-CN>显示图片高度字段标签。</zh-CN><en>Displays the image-height field label.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label HeightLabel;

        /// <summary><lang><zh-CN>图片高度输入框。</zh-CN><en>Input for the image height.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox Height;

        /// <summary><lang><zh-CN>显示图片来源或尺寸校验消息的标签。</zh-CN><en>Label that displays image-source or dimension validation messages.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ValidationMessage;

        /// <summary><lang><zh-CN>提交图片设置更改的按钮。</zh-CN><en>Button that submits image-setting changes.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton updateButton;

        /// <summary><lang><zh-CN>取消图片设置编辑的按钮。</zh-CN><en>Button that cancels image-setting editing.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton cancelButton;
    }
}
