//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class EditXml
    {

        /// <summary><lang><zh-CN>显示 XML 数据源路径字段标签。</zh-CN><en>Displays the label for the XML data-source path field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label XmlDataSrcLabel;

        /// <summary><lang><zh-CN>接收 XML 数据源路径的输入框；路径约束由页面和安全策略共同决定。</zh-CN><en>Input for the XML data-source path; effective path constraints are defined by the page and security policies.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox XmlDataSrc;

        /// <summary><lang><zh-CN>显示 XSL 转换源路径字段标签。</zh-CN><en>Displays the label for the XSL-transform source path field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label XslTransformSrcLabel;

        /// <summary><lang><zh-CN>接收 XSL 转换源路径的输入框；路径约束由页面和安全策略共同决定。</zh-CN><en>Input for the XSL-transform source path; effective path constraints are defined by the page and security policies.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox XslTransformSrc;

        /// <summary><lang><zh-CN>显示 XML/XSL 输入校验结果或安全错误提示。</zh-CN><en>Displays XML/XSL input-validation results or safe security-error guidance.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ValidationMessage;

        /// <summary><lang><zh-CN>提交 XML 模块配置更新的受控按钮。</zh-CN><en>Controlled button that submits the XML-module configuration update.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton updateButton;

        /// <summary><lang><zh-CN>取消当前 XML 模块配置编辑的按钮。</zh-CN><en>Button that cancels the current XML-module configuration edit.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton cancelButton;
    }
}
