//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class EditDocs
    {

        /// <summary><lang><zh-CN>文档名称输入框。</zh-CN><en>Document-name input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox NameField;

        /// <summary><lang><zh-CN>文档名称必填校验器。</zh-CN><en>Required-field validator for the document name.</en></lang></summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        /// <summary><lang><zh-CN>文档分类输入框。</zh-CN><en>Document-category input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox CategoryField;

        /// <summary><lang><zh-CN>文档路径输入框；实际路径约束由页面逻辑和安全策略共同决定。</zh-CN><en>Document-path input field; effective path constraints are defined by page logic and security policy.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox PathField;

        /// <summary><lang><zh-CN>展示文档上传策略和限制的只读提示。</zh-CN><en>Read-only hint that presents document-upload policy and restrictions.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label UploadPolicyHint;

        /// <summary><lang><zh-CN>启用文档上传流程的复选框。</zh-CN><en>Check box that enables the document-upload flow.</en></lang></summary>
        protected global::System.Web.UI.WebControls.CheckBox Upload;

        /// <summary><lang><zh-CN>选择将上传内容保存到数据库的复选框。</zh-CN><en>Check box that selects database storage for uploaded content.</en></lang></summary>
        protected global::System.Web.UI.WebControls.CheckBox storeInDatabase;

        /// <summary><lang><zh-CN>接收待上传文档的 HTML 文件输入控件。</zh-CN><en>HTML file input that receives the document to upload.</en></lang></summary>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile FileUpload;

        /// <summary><lang><zh-CN>显示文档上传处理结果或失败原因的消息标签。</zh-CN><en>Message label for document-upload results or failure reasons.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label UploadMessage;

        /// <summary><lang><zh-CN>提交文档编辑或上传内容的命令按钮。</zh-CN><en>Command button that submits document edits or upload content.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton updateButton;

        /// <summary><lang><zh-CN>取消文档编辑的命令按钮。</zh-CN><en>Command button that cancels document editing.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton cancelButton;

        /// <summary><lang><zh-CN>删除当前文档的命令按钮。</zh-CN><en>Command button that deletes the current document.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton deleteButton;

        /// <summary><lang><zh-CN>显示文档创建者的只读标签。</zh-CN><en>Read-only label that displays the document creator.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label CreatedBy;

        /// <summary><lang><zh-CN>显示文档创建时间的只读标签。</zh-CN><en>Read-only label that displays the document creation time.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label CreatedDate;
    }
}
