//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class EditAnnouncements
    {

        /// <summary><lang><zh-CN>公告标题输入框。</zh-CN><en>Announcement-title input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox TitleField;

        /// <summary><lang><zh-CN>公告标题必填校验器。</zh-CN><en>Required-field validator for the announcement title.</en></lang></summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Req1;

        /// <summary><lang><zh-CN>桌面端“更多”链接输入框。</zh-CN><en>Desktop “more” link input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox MoreLinkField;

        /// <summary><lang><zh-CN>移动端“更多”链接输入框。</zh-CN><en>Mobile “more” link input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox MobileMoreField;

        /// <summary><lang><zh-CN>公告描述输入框。</zh-CN><en>Announcement-description input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox DescriptionField;

        /// <summary><lang><zh-CN>公告描述必填校验器。</zh-CN><en>Required-field validator for the announcement description.</en></lang></summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Req2;

        /// <summary><lang><zh-CN>公告过期日期输入框。</zh-CN><en>Announcement-expiration date input field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox ExpireField;

        /// <summary><lang><zh-CN>公告过期日期必填校验器。</zh-CN><en>Required-field validator for the announcement expiration date.</en></lang></summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredExpireDate;

        /// <summary><lang><zh-CN>公告过期日期格式或范围校验器。</zh-CN><en>Validator for the announcement expiration-date format or range.</en></lang></summary>
        protected global::System.Web.UI.WebControls.CompareValidator VerifyExpireDate;

        /// <summary><lang><zh-CN>显示公告字段校验结果的消息标签。</zh-CN><en>Message label for announcement-field validation results.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ValidationMessage;

        /// <summary><lang><zh-CN>提交公告编辑内容的命令按钮。</zh-CN><en>Command button that submits announcement edits.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton updateButton;

        /// <summary><lang><zh-CN>取消公告编辑的命令按钮。</zh-CN><en>Command button that cancels announcement editing.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton cancelButton;

        /// <summary><lang><zh-CN>删除当前公告的命令按钮。</zh-CN><en>Command button that deletes the current announcement.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton deleteButton;

        /// <summary><lang><zh-CN>显示公告创建者的只读标签。</zh-CN><en>Read-only label that displays the announcement creator.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label CreatedBy;

        /// <summary><lang><zh-CN>显示公告创建时间的只读标签。</zh-CN><en>Read-only label that displays the announcement creation time.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label CreatedDate;
    }
}
