//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal {
    
    
    public partial class HtmlModule {
        
        /// <summary><lang><zh-CN>显示 HTML 模块标题的共享标题组件。</zh-CN><en>Shared title component that displays the HTML-module title.</en></lang></summary>
        protected global::ASPNET.StarterKit.Portal.DesktopModuleTitle Title1;
        
        /// <summary><lang><zh-CN>承载模块渲染 HTML 内容的服务端容器。</zh-CN><en>Server-side container that holds the module-rendered HTML content.</en></lang></summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl HtmlHolder;
    }
}
