//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal {


    public partial class QuickLinks {

        /// <summary><lang><zh-CN>承载快捷链接编辑操作入口的面板。</zh-CN><en>Panel that contains quick-link editing actions.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel QuickLinkActions;

        /// <summary><lang><zh-CN>指向快捷链接编辑入口的链接。</zh-CN><en>Link to the quick-link editing entry point.</en></lang></summary>
        protected global::System.Web.UI.WebControls.HyperLink EditButton;

        /// <summary><lang><zh-CN>绑定快捷链接条目的 DataList。</zh-CN><en>DataList bound to quick-link entries.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DataList myDataList;
    }
}
