//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class Signin
    {

        /// <summary><lang><zh-CN>接收登录邮箱或用户名的输入框。</zh-CN><en>Input field for the sign-in email address or user name.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox EmailOrName;

        /// <summary><lang><zh-CN>接收登录口令的密码输入框；页面逻辑负责其安全提交与处理。</zh-CN><en>Password input used for sign-in; page logic is responsible for secure submission and handling.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox password;

        /// <summary><lang><zh-CN>承载前端加密口令载荷的隐藏字段；不应被当作明文口令存储。</zh-CN><en>Hidden field carrying the client-side encrypted password payload; it must not be treated as plaintext password storage.</en></lang></summary>
        protected global::System.Web.UI.WebControls.HiddenField EncryptedPassword;

        /// <summary><lang><zh-CN>请求记住登录状态的复选框。</zh-CN><en>Check box requesting a remembered sign-in state.</en></lang></summary>
        protected global::System.Web.UI.WebControls.CheckBox RememberCheckbox;

        /// <summary><lang><zh-CN>提交登录请求的按钮。</zh-CN><en>Button that submits the sign-in request.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Button SigninBtn;

        /// <summary><lang><zh-CN>导航到公开注册页面的链接。</zh-CN><en>Link that navigates to the public registration page.</en></lang></summary>
        protected global::System.Web.UI.WebControls.HyperLink RegisterLink;

        /// <summary><lang><zh-CN>显示登录失败、成功或后续提示的消息标签。</zh-CN><en>Message label for sign-in failure, success, or follow-up guidance.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label Message;
    }
}
