//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的容器文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added container documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal {

    /// <summary>
    /// <lang>
    ///   <zh-CN>文档下载页的 Designer partial 容器；页面通过 code-behind 写响应流，不声明生成字段。</zh-CN>
    ///   <en>Designer partial container for the document-download page; the page writes the response stream through code-behind and declares no generated fields.</en>
    /// </lang>
    /// </summary>
    public partial class ViewDocument {
    }
}
