//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal {
    
    
    public partial class XmlModule {
        
        /// <summary><lang><zh-CN>显示 XML 模块标题的共享标题组件。</zh-CN><en>Shared title component that displays the XML-module title.</en></lang></summary>
        protected global::ASPNET.StarterKit.Portal.DesktopModuleTitle Title1;
        
        /// <summary><lang><zh-CN>承载模块配置 XML 输出的呈现组件。</zh-CN><en>Rendering component that presents the module-configured XML output.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Xml xml1;
    }
}
