//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class BusinessApplications
    {
        /// <summary>页面级状态提示。Page-level status message.</summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>状态筛选控件。Status filter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList StatusFilterList;

        /// <summary>搜索按钮。Search button.</summary>
        protected global::System.Web.UI.WebControls.Button SearchButton;

        /// <summary>结果摘要提示。Result summary label.</summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary>申请列表控件。Application list control.</summary>
        protected global::System.Web.UI.WebControls.Repeater ApplicationsRepeater;
    }
}
