//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class BusinessApplications
    {
        /// <summary><lang><zh-CN>显示业务申请页面级状态提示。</zh-CN><en>Displays the business-application page-level status message.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary><lang><zh-CN>按业务申请状态筛选列表。</zh-CN><en>Filters the list by business-application status.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList StatusFilterList;

        /// <summary><lang><zh-CN>提交业务申请状态筛选查询的按钮。</zh-CN><en>Button that submits the business-application status filter query.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Button SearchButton;

        /// <summary><lang><zh-CN>显示业务申请查询结果摘要。</zh-CN><en>Displays the business-application query result summary.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary><lang><zh-CN>绑定业务申请查询结果行的 Repeater。</zh-CN><en>Repeater bound to business-application query result rows.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater ApplicationsRepeater;
    }
}
