//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class CapabilityPermissionMatrix
    {
        /// <summary><lang><zh-CN>承载矩阵 HTML 的只读输出区（PassThrough，渲染器已完成编码）。</zh-CN><en>Read-only output area carrying the matrix HTML (PassThrough; the renderer already encoded it).</en></lang></summary>
        protected global::System.Web.UI.WebControls.Literal MatrixLiteral;

        /// <summary><lang><zh-CN>权限映射表不可用或无映射时的提示标签。</zh-CN><en>Hint label shown when the permission mapping table is unavailable or holds no mapping.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label UnavailableLabel;
    }
}
