//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class CollaborationItems
    {
        /// <summary>页面级状态提示。Page-level status message.</summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>事项类型输入框。Item type input.</summary>
        protected global::System.Web.UI.WebControls.TextBox ItemTypeKeyTextBox;

        /// <summary>负责人角色输入框。Owner role input.</summary>
        protected global::System.Web.UI.WebControls.TextBox OwnerRoleKeyTextBox;

        /// <summary>优先级选择控件。Priority selector.</summary>
        protected global::System.Web.UI.WebControls.DropDownList PriorityList;

        /// <summary>期限输入框。Due UTC input.</summary>
        protected global::System.Web.UI.WebControls.TextBox DueUtcTextBox;

        /// <summary>标题输入框。Title input.</summary>
        protected global::System.Web.UI.WebControls.TextBox TitleTextBox;

        /// <summary>摘要输入框。Summary input.</summary>
        protected global::System.Web.UI.WebControls.TextBox SummaryTextBox;

        /// <summary>说明输入框。Description input.</summary>
        protected global::System.Web.UI.WebControls.TextBox DescriptionTextBox;

        /// <summary>创建按钮。Create button.</summary>
        protected global::System.Web.UI.WebControls.Button CreateButton;

        /// <summary>状态筛选控件。Status filter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList StatusFilterList;

        /// <summary>搜索按钮。Search button.</summary>
        protected global::System.Web.UI.WebControls.Button SearchButton;

        /// <summary>结果摘要提示。Result summary label.</summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary>协同事项列表控件。Collaboration item list control.</summary>
        protected global::System.Web.UI.WebControls.Repeater ItemsRepeater;
    }
}
