//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class CollaborationItems
    {
        /// <summary><lang><zh-CN>页面级协同事项状态提示。</zh-CN><en>Page-level collaboration-item status message.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary><lang><zh-CN>协同事项类型选择控件。</zh-CN><en>Collaboration-item type selector.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList ItemTypeList;

        /// <summary><lang><zh-CN>协同事项负责人角色输入框。</zh-CN><en>Owner-role input for the collaboration item.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox OwnerRoleKeyTextBox;

        /// <summary><lang><zh-CN>协同事项优先级选择控件。</zh-CN><en>Collaboration-item priority selector.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList PriorityList;

        /// <summary><lang><zh-CN>协同事项期限 UTC 输入框。</zh-CN><en>UTC due-time input for the collaboration item.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox DueUtcTextBox;

        /// <summary><lang><zh-CN>协同事项标题输入框。</zh-CN><en>Collaboration-item title input.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox TitleTextBox;

        /// <summary><lang><zh-CN>协同事项摘要输入框。</zh-CN><en>Collaboration-item summary input.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox SummaryTextBox;

        /// <summary><lang><zh-CN>协同事项详细说明输入框。</zh-CN><en>Collaboration-item description input.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox DescriptionTextBox;

        /// <summary><lang><zh-CN>提交创建协同事项的按钮。</zh-CN><en>Button that submits collaboration-item creation.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Button CreateButton;

        /// <summary><lang><zh-CN>协同事项状态筛选控件。</zh-CN><en>Collaboration-item status filter.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList StatusFilterList;

        /// <summary><lang><zh-CN>提交协同事项筛选查询的按钮。</zh-CN><en>Button that submits the collaboration-item filter query.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Button SearchButton;

        /// <summary><lang><zh-CN>显示协同事项查询结果摘要的标签。</zh-CN><en>Label that displays the collaboration-item result summary.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary><lang><zh-CN>绑定协同事项结果行的 Repeater。</zh-CN><en>Repeater bound to collaboration-item result rows.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater ItemsRepeater;
    }
}
