//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class DiagnosticLogDetail
    {
        protected global::System.Web.UI.WebControls.Label MessageLabel;
        protected global::System.Web.UI.WebControls.Panel DetailPanel;
        protected global::System.Web.UI.WebControls.Label EventIdLabel;
        protected global::System.Web.UI.WebControls.Label UtcTimeLabel;
        protected global::System.Web.UI.WebControls.Label LevelLabel;
        protected global::System.Web.UI.WebControls.Label CategoryLabel;
        protected global::System.Web.UI.WebControls.Label MessageTextLabel;
        protected global::System.Web.UI.WebControls.Label ExceptionTypeLabel;
        protected global::System.Web.UI.WebControls.TextBox ExceptionDetailTextBox;
        protected global::System.Web.UI.WebControls.Label RequestPathLabel;
        protected global::System.Web.UI.WebControls.Label HttpMethodLabel;
        protected global::System.Web.UI.WebControls.Label UserNameLabel;
        protected global::System.Web.UI.WebControls.Label ClientIpLabel;
        protected global::System.Web.UI.WebControls.Label PhysicalPathLabel;
        protected global::System.Web.UI.WebControls.Label UserAgentLabel;
        protected global::System.Web.UI.WebControls.HyperLink BackLink;
    }
}
