//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class EmployeeProfileCorrectionRequests
    {
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        protected global::System.Web.UI.WebControls.DropDownList StatusFilterList;

        protected global::System.Web.UI.WebControls.LinkButton SearchButton;

        protected global::System.Web.UI.WebControls.Label ResultLabel;

        protected global::System.Web.UI.WebControls.Repeater RequestsRepeater;
    }
}
