//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class EmployeeDirectory
    {
        /// <summary>中文：页面级提示信息。English: Page-level message text.</summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>中文：目录关键字筛选框。English: Directory keyword filter box.</summary>
        protected global::System.Web.UI.WebControls.TextBox KeywordTextBox;

        /// <summary>中文：员工状态筛选下拉框。English: Employee-status filter drop-down.</summary>
        protected global::System.Web.UI.WebControls.DropDownList EmployeeStatusList;

        /// <summary>中文：账号员工绑定状态筛选下拉框。English: User-employee binding-status filter drop-down.</summary>
        protected global::System.Web.UI.WebControls.DropDownList BindingStatusList;

        /// <summary>中文：是否包含停用组织。English: Whether inactive organization units are included.</summary>
        protected global::System.Web.UI.WebControls.CheckBox IncludeInactiveOrganizations;

        /// <summary>中文：只读查询按钮。English: Read-only search button.</summary>
        protected global::System.Web.UI.WebControls.LinkButton SearchButton;

        /// <summary>中文：P6.3 数据表状态提示。English: P6.3 schema status message.</summary>
        protected global::System.Web.UI.WebControls.Label SchemaStatusLabel;

        /// <summary>中文：只读查询结果统计。English: Read-only query result summary.</summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary>中文：组织单元只读列表。English: Read-only organization-unit list.</summary>
        protected global::System.Web.UI.WebControls.Repeater OrganizationsRepeater;

        /// <summary>中文：员工只读列表。English: Read-only employee list.</summary>
        protected global::System.Web.UI.WebControls.Repeater EmployeesRepeater;

        /// <summary>中文：账号员工绑定只读列表。English: Read-only user-employee binding list.</summary>
        protected global::System.Web.UI.WebControls.Repeater BindingsRepeater;
    }
}
