//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class EmployeeDirectory
    {
        /// <summary>
        /// <lang><zh-CN>页面级提示信息。</zh-CN><en>Page-level message text.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// <lang><zh-CN>目录关键字筛选框。</zh-CN><en>Directory keyword filter box.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox KeywordTextBox;

        /// <summary>
        /// <lang><zh-CN>员工状态筛选下拉框。</zh-CN><en>Employee-status filter drop-down.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList EmployeeStatusList;

        /// <summary>
        /// <lang><zh-CN>账号员工绑定状态筛选下拉框。</zh-CN><en>User-employee binding-status filter drop-down.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList BindingStatusList;

        /// <summary>
        /// <lang><zh-CN>是否包含停用组织。</zh-CN><en>Whether inactive organization units are included.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox IncludeInactiveOrganizations;

        /// <summary>
        /// <lang><zh-CN>只读查询按钮。</zh-CN><en>Read-only search button.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton SearchButton;

        /// <summary>
        /// <lang><zh-CN>P6.3 数据表状态提示。</zh-CN><en>P6.3 schema status message.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label SchemaStatusLabel;

        /// <summary>
        /// <lang><zh-CN>只读查询结果统计。</zh-CN><en>Read-only query result summary.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary>
        /// <lang><zh-CN>组织单元只读列表。</zh-CN><en>Read-only organization-unit list.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater OrganizationsRepeater;

        /// <summary>
        /// <lang><zh-CN>员工只读列表。</zh-CN><en>Read-only employee list.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater EmployeesRepeater;

        /// <summary>
        /// <lang><zh-CN>账号员工绑定只读列表。</zh-CN><en>Read-only user-employee binding list.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater BindingsRepeater;
    }
}
