// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>

namespace ASPNET.StarterKit.Portal
{
    public partial class ManageUsers
    {
        /// <summary>
        /// <lang><zh-CN>显示用户管理页标题。</zh-CN><en>Displays the user-management page title.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label TitleText;

        /// <summary>
        /// <lang><zh-CN>显示注册审核状态提示。</zh-CN><en>Displays the registration-review status message.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label RegistrationStatus;

        /// <summary>
        /// <lang><zh-CN>触发受控注册批准动作的按钮。</zh-CN><en>Button that starts the controlled registration-approval action.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton ApproveRegistrationBtn;

        /// <summary>
        /// <lang><zh-CN>触发受控注册拒绝动作的按钮。</zh-CN><en>Button that starts the controlled registration-rejection action.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton RejectRegistrationBtn;

        /// <summary>
        /// <lang><zh-CN>显示注册来源的低敏文本。</zh-CN><en>Displays the low-sensitivity registration source text.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label RegistrationSource;

        /// <summary>
        /// <lang><zh-CN>显示注册记录关联的员工号。</zh-CN><en>Displays the employee code associated with the registration record.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label EmployeeCodeText;

        /// <summary>
        /// <lang><zh-CN>显示用户—员工绑定状态。</zh-CN><en>Displays the user-to-employee binding status.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label EmployeeBindingText;

        /// <summary>
        /// <lang><zh-CN>指向受控员工绑定编辑入口的链接。</zh-CN><en>Links to the controlled employee-binding editor.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink EmployeeBindingLink;

        /// <summary>
        /// <lang><zh-CN>显示注册邀请代码的受控文本区域。</zh-CN><en>Displays the registration invitation code in a controlled text area.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label InviteCodeText;

        /// <summary>
        /// <lang><zh-CN>显示注册提交 UTC 时间。</zh-CN><en>Displays the registration-submission time in UTC.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label RegisteredUtcText;

        /// <summary>
        /// <lang><zh-CN>显示批准完成 UTC 时间。</zh-CN><en>Displays the approval-completion time in UTC.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ApprovedUtcText;

        /// <summary>
        /// <lang><zh-CN>显示注册审核结果消息。</zh-CN><en>Displays the registration-review result message.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label RegistrationMessage;

        /// <summary>
        /// <lang><zh-CN>显示历史用户登录名。</zh-CN><en>Displays the legacy user's login name.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LegacyUserNameText;

        /// <summary>
        /// <lang><zh-CN>编辑用户登录名的输入框。</zh-CN><en>Input for editing the user's login name.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox LoginName;

        /// <summary>
        /// <lang><zh-CN>编辑用户显示名的输入框。</zh-CN><en>Input for editing the user's display name.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox DisplayName;

        /// <summary>
        /// <lang><zh-CN>编辑用户首选名称的输入框。</zh-CN><en>Input for editing the user's preferred name.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Nickname;

        /// <summary>
        /// <lang><zh-CN>显示用户资料状态。</zh-CN><en>Displays the user-profile status.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ProfileStatusText;

        /// <summary>
        /// <lang><zh-CN>显示用户资料来源。</zh-CN><en>Displays the user-profile source.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ProfileSourceText;

        /// <summary>
        /// <lang><zh-CN>以受控权限动作停用用户。</zh-CN><en>Disables the user through a controlled permission-gated action.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton DisableUserBtn;

        /// <summary>
        /// <lang><zh-CN>以受控权限动作恢复用户。</zh-CN><en>Restores the user through a controlled permission-gated action.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton RestoreUserBtn;

        /// <summary>
        /// <lang><zh-CN>编辑用户工作邮箱的输入框。</zh-CN><en>Input for editing the user's work email.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Email;

        /// <summary>
        /// <lang><zh-CN>接收新口令的受控输入框；值不得进入日志或普通响应。</zh-CN><en>Controlled input for a new password; its value must not enter logs or ordinary responses.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Password;

        /// <summary>
        /// <lang><zh-CN>承载前端口令加密结果的隐藏字段，服务端必须重新校验其可信边界。</zh-CN><en>Hidden field carrying the client-side password-encryption result; the server must revalidate its trust boundary.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField EncryptedPassword;

        /// <summary>
        /// <lang><zh-CN>校验新口令是否已提供。</zh-CN><en>Validates that a new password was supplied.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        /// <summary>
        /// <lang><zh-CN>接收重复口令的受控输入框。</zh-CN><en>Controlled input for repeating the password.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;

        /// <summary>
        /// <lang><zh-CN>承载前端重复口令加密结果的隐藏字段。</zh-CN><en>Hidden field carrying the client-side encrypted repeated-password result.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField EncryptedConfirmPassword;

        /// <summary>
        /// <lang><zh-CN>校验重复口令是否已提供。</zh-CN><en>Validates that the repeated password was supplied.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;

        /// <summary>
        /// <lang><zh-CN>校验两次口令输入是否一致。</zh-CN><en>Validates that the two password inputs match.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.CompareValidator CompareValidator1;

        /// <summary>
        /// <lang><zh-CN>提交用户资料编辑的受控按钮。</zh-CN><en>Controlled button that submits user-profile edits.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton UpdateUserBtn;

        /// <summary>
        /// <lang><zh-CN>提供可分配角色的受控选择列表。</zh-CN><en>Controlled list of roles that may be assigned.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList allRoles;

        /// <summary>
        /// <lang><zh-CN>将选定角色加入用户角色集合的按钮。</zh-CN><en>Button that adds the selected role to the user's role set.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton addExisting;

        /// <summary>
        /// <lang><zh-CN>显示用户当前角色集合的数据列表。</zh-CN><en>Data list that displays the user's current role set.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.DataList userRoles;

        /// <summary>
        /// <lang><zh-CN>提交角色编辑结果的受控按钮。</zh-CN><en>Controlled button that submits role-edit results.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton saveBtn;
    }
}
