//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class ModuleCatalog
    {
        /// <summary><lang><zh-CN>显示模块目录页面级安全错误提示。</zh-CN><en>Displays the module-catalog page-level safe error message.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary><lang><zh-CN>显示模块目录操作结果提示。</zh-CN><en>Displays the module-catalog action result message.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary><lang><zh-CN>绑定已验证模块包目录行的 GridView。</zh-CN><en>GridView bound to validated module-package catalog rows.</en></lang></summary>
        protected global::System.Web.UI.WebControls.GridView PackagesGrid;
    }
}
