//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class ModuleDefs
    {

        /// <summary><lang><zh-CN>显示模块定义控件标题的共享标题组件。</zh-CN><en>Shared title component that displays the module-definition control title.</en></lang></summary>
        protected global::ASPNET.StarterKit.Portal.DesktopModuleTitle Title1;

        /// <summary><lang><zh-CN>绑定模块定义列表的 DataList。</zh-CN><en>DataList bound to the module-definition list.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DataList defsList;

        /// <summary><lang><zh-CN>触发新增模块定义入口的按钮。</zh-CN><en>Button that opens the add-module-definition entry point.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton AddDefBtn;
    }
}
