//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class ModuleSettingsPage
    {
        /// <summary><lang><zh-CN>显示模块设置操作状态消息。</zh-CN><en>Displays the module-settings operation status.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label Message;

        /// <summary><lang><zh-CN>当前模块标题输入框。</zh-CN><en>Input for the current module title.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox moduleTitle;

        /// <summary><lang><zh-CN>模块输出缓存时间输入框。</zh-CN><en>Input for the module output-cache duration.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox cacheTime;

        /// <summary><lang><zh-CN>选择可编辑当前模块设置的授权角色。</zh-CN><en>Selects the roles authorized to edit the current module settings.</en></lang></summary>
        protected global::System.Web.UI.WebControls.CheckBoxList authEditRoles;

        /// <summary><lang><zh-CN>控制当前模块是否显示在移动端的复选框。</zh-CN><en>Checkbox that controls whether the current module is shown on mobile.</en></lang></summary>
        protected global::System.Web.UI.WebControls.CheckBox showMobile;

        /// <summary><lang><zh-CN>应用当前模块设置更改的按钮。</zh-CN><en>Button that applies the current module-setting changes.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton ApplyButton;
    }
}
