//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class ModuleCatalog
    {
        /// <summary>
        /// 页面级安全错误提示。
        /// Page-level safe error message.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// 页面级操作结果提示。
        /// Page-level action result message.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary>
        /// 已验证模块包目录表格。
        /// Validated module-package catalog grid.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView PackagesGrid;
    }
}
