//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class OperationAudits
    {
        protected global::System.Web.UI.WebControls.TextBox StartDateTextBox;
        protected global::System.Web.UI.WebControls.TextBox EndDateTextBox;
        protected global::System.Web.UI.WebControls.TextBox CategoryFilter;
        protected global::System.Web.UI.WebControls.TextBox ActionFilter;
        protected global::System.Web.UI.WebControls.TextBox TargetIdFilter;
        protected global::System.Web.UI.WebControls.LinkButton SearchButton;
        protected global::System.Web.UI.WebControls.Label MessageLabel;
        protected global::System.Web.UI.WebControls.Label ResultLabel;
        protected global::System.Web.UI.WebControls.LinkButton PreviousButton;
        protected global::System.Web.UI.WebControls.LinkButton NextButton;
        protected global::System.Web.UI.WebControls.Repeater EntriesRepeater;
    }
}
