//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class OrganizationUnitEdit
    {
        /// <summary>中文：页面标题。English: Page title.</summary>
        protected global::System.Web.UI.WebControls.Label TitleLabel;

        /// <summary>中文：页面级安全提示。English: Page-level safe message.</summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>中文：组织单元标识隐藏字段。English: Hidden organization-unit identifier field.</summary>
        protected global::System.Web.UI.WebControls.HiddenField OrganizationUnitIdField;

        /// <summary>中文：编辑前 UTC 更新时间隐藏字段。English: Hidden pre-edit UTC update-time field.</summary>
        protected global::System.Web.UI.WebControls.HiddenField OriginalUpdatedUtcField;

        /// <summary>中文：组织编码输入框。English: Organization-code input.</summary>
        protected global::System.Web.UI.WebControls.TextBox OrganizationCodeTextBox;

        /// <summary>中文：组织显示名输入框。English: Organization display-name input.</summary>
        protected global::System.Web.UI.WebControls.TextBox DisplayNameTextBox;

        /// <summary>中文：父级组织选择器。English: Parent organization selector.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ParentOrganizationList;

        /// <summary>中文：排序值输入框。English: Sort-order input.</summary>
        protected global::System.Web.UI.WebControls.TextBox SortOrderTextBox;

        /// <summary>中文：启用状态复选框。English: Active-state checkbox.</summary>
        protected global::System.Web.UI.WebControls.CheckBox IsActiveCheckBox;

        /// <summary>中文：保存按钮。English: Save button.</summary>
        protected global::System.Web.UI.WebControls.LinkButton SaveButton;
    }
}
