// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>

namespace ASPNET.StarterKit.Portal
{
    public partial class Register
    {
        /// <summary>
        /// <lang><zh-CN>接收公开注册姓名的输入框。</zh-CN><en>Input for the public-registration name.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Name;

        /// <summary>
        /// <lang><zh-CN>校验姓名是否已提供。</zh-CN><en>Validates that the name was supplied.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        /// <summary>
        /// <lang><zh-CN>接收公开注册邮箱的输入框。</zh-CN><en>Input for the public-registration email.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Email;

        /// <summary>
        /// <lang><zh-CN>按页面约束校验邮箱格式。</zh-CN><en>Validates the email format against the page contract.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;

        /// <summary>
        /// <lang><zh-CN>校验邮箱是否已提供。</zh-CN><en>Validates that the email was supplied.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;

        /// <summary>
        /// <lang><zh-CN>说明员工号是否为当前注册策略要求的字段。</zh-CN><en>Explains whether employee code is required by the current registration policy.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label EmployeeCodeRequiredHint;

        /// <summary>
        /// <lang><zh-CN>接收注册关联员工号的输入框。</zh-CN><en>Input for the employee code associated with the registration.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmployeeCode;

        /// <summary>
        /// <lang><zh-CN>校验要求员工号策略下的输入是否存在。</zh-CN><en>Validates that employee code is present when the policy requires it.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator EmployeeCodeRequiredValidator;

        /// <summary>
        /// <lang><zh-CN>接收注册口令的受控输入框；值不得进入日志或普通响应。</zh-CN><en>Controlled input for the registration password; its value must not enter logs or ordinary responses.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Password;

        /// <summary>
        /// <lang><zh-CN>承载前端口令加密结果的隐藏字段，服务端必须重新校验其可信边界。</zh-CN><en>Hidden field carrying the client-side password-encryption result; the server must revalidate its trust boundary.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField EncryptedPassword;

        /// <summary>
        /// <lang><zh-CN>校验注册口令是否已提供。</zh-CN><en>Validates that the registration password was supplied.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;

        /// <summary>
        /// <lang><zh-CN>接收重复注册口令的受控输入框。</zh-CN><en>Controlled input for repeating the registration password.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;

        /// <summary>
        /// <lang><zh-CN>承载前端重复口令加密结果的隐藏字段。</zh-CN><en>Hidden field carrying the client-side encrypted repeated-password result.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField EncryptedConfirmPassword;

        /// <summary>
        /// <lang><zh-CN>校验重复注册口令是否已提供。</zh-CN><en>Validates that the repeated registration password was supplied.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;

        /// <summary>
        /// <lang><zh-CN>校验两次注册口令输入是否一致。</zh-CN><en>Validates that the two registration-password inputs match.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.CompareValidator CompareValidator1;

        /// <summary>
        /// <lang><zh-CN>提交公开注册请求的受控按钮。</zh-CN><en>Controlled button that submits the public-registration request.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton RegisterBtn;

        /// <summary>
        /// <lang><zh-CN>显示注册结果或受控提示消息。</zh-CN><en>Displays the registration result or a controlled status message.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Message;
    }
}
