//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class Roles
    {
        /// <summary><lang><zh-CN>显示角色管理控件标题。</zh-CN><en>Displays the role-management control title.</en></lang></summary>
        protected global::ASPNET.StarterKit.Portal.DesktopModuleTitle Title1;

        /// <summary><lang><zh-CN>显示角色管理操作状态消息。</zh-CN><en>Displays the role-management operation status.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label Message;

        /// <summary><lang><zh-CN>显示当前门户角色列表的数据列表。</zh-CN><en>Data list that displays the current portal roles.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DataList rolesList;

        /// <summary><lang><zh-CN>打开新建角色入口的按钮。</zh-CN><en>Button that opens the new-role entry point.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton AddRoleBtn;
    }
}
