//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class SecurityRoles
    {

        /// <summary><lang><zh-CN>显示当前角色标题的 HTML 容器。</zh-CN><en>HTML container that displays the current role title.</en></lang></summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl title;

        /// <summary><lang><zh-CN>显示角色成员操作结果或失败原因的消息标签。</zh-CN><en>Message label for role-member operation results or failure reasons.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label Message;

        /// <summary><lang><zh-CN>供管理员选择待加入当前角色的用户下拉列表。</zh-CN><en>Drop-down list from which an administrator selects a user to add to the current role.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList allUsers;

        /// <summary><lang><zh-CN>将所选用户加入当前角色的命令按钮。</zh-CN><en>Command button that adds the selected user to the current role.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton addExisting;

        /// <summary><lang><zh-CN>显示当前角色成员并承载成员操作绑定的数据列表。</zh-CN><en>Data list that displays current role members and carries member-operation bindings.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DataList usersInRole;

        /// <summary><lang><zh-CN>提交当前角色成员变更的命令按钮。</zh-CN><en>Command button that submits current role-member changes.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton saveBtn;
    }
}
