//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal {
    
    
    public partial class SiteSettings {
        
        /// <summary><lang><zh-CN>显示站点设置控件标题的共享标题组件。</zh-CN><en>Shared title component that displays the site-settings control title.</en></lang></summary>
        protected global::ASPNET.StarterKit.Portal.DesktopModuleTitle Title1;

        /// <summary><lang><zh-CN>显示站点设置操作状态消息。</zh-CN><en>Displays the site-settings operation status message.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label Message;
        
        /// <summary><lang><zh-CN>接收站点名称设置的输入框。</zh-CN><en>Input for the site-name setting.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox SiteName;
        
        /// <summary><lang><zh-CN>选择是否显示编辑入口的复选框。</zh-CN><en>Check box that selects whether the edit entry point is shown.</en></lang></summary>
        protected global::System.Web.UI.WebControls.CheckBox showEdit;
        
        /// <summary><lang><zh-CN>提交站点设置更改的按钮。</zh-CN><en>Button that submits site-settings changes.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton applyBtn;
    }
}
