//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class SystemHealth
    {
        /// <summary><lang><zh-CN>显示系统健康总体状态。</zh-CN><en>Displays the overall system-health status.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label OverallStatusLabel;

        /// <summary><lang><zh-CN>显示健康快照生成 UTC 时间。</zh-CN><en>Displays the UTC time when the health snapshot was generated.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label GeneratedUtcLabel;

        /// <summary><lang><zh-CN>触发系统健康快照刷新的按钮。</zh-CN><en>Button that refreshes the system-health snapshot.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton RefreshButton;

        /// <summary><lang><zh-CN>绑定系统健康检查结果行的 Repeater。</zh-CN><en>Repeater bound to system-health check result rows.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater HealthChecksRepeater;

        /// <summary><lang><zh-CN>绑定运行设置诊断结果行的 Repeater。</zh-CN><en>Repeater bound to runtime-settings diagnostic result rows.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater SettingsRepeater;
    }
}
