//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class SystemHealth
    {
        protected global::System.Web.UI.WebControls.Label OverallStatusLabel;

        protected global::System.Web.UI.WebControls.Label GeneratedUtcLabel;

        protected global::System.Web.UI.WebControls.LinkButton RefreshButton;

        protected global::System.Web.UI.WebControls.Repeater HealthChecksRepeater;

        protected global::System.Web.UI.WebControls.Repeater SettingsRepeater;
    }
}
