//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class ThemeSettings
    {
        /// <summary>
        /// 页面级安全提示。
        /// Page-level safe status message.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// 已部署全局主题选择器。
        /// Deployed global-theme selector.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList GlobalThemeList;

        /// <summary>
        /// 保存全局主题操作。
        /// Save-global-theme action.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton SaveGlobalThemeButton;

        /// <summary>
        /// 清除全局覆盖操作。
        /// Clear-global-override action.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton ResetGlobalThemeButton;

        /// <summary>
        /// 全局主题来源状态。
        /// Global-theme source status.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label GlobalThemeStatusLabel;

        /// <summary>
        /// 门户 Tab 选择器。
        /// Portal Tab selector.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList TabList;

        /// <summary>
        /// Tab 覆盖主题选择器。
        /// Tab override-theme selector.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList TabThemeList;

        /// <summary>
        /// 保存 Tab 覆盖操作。
        /// Save-Tab-override action.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton SaveTabThemeButton;

        /// <summary>
        /// 清除 Tab 覆盖操作。
        /// Clear-Tab-override action.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton ClearTabThemeButton;

        /// <summary>
        /// 当前 Tab 覆盖状态。
        /// Current Tab-override status.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label TabThemeStatusLabel;
    }
}
