//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class UserEmployeeBindingEdit
    {
        /// <summary>
        /// <lang><zh-CN>返回用户管理页链接。</zh-CN><en>Link back to user administration.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink ManageUserLink;

        /// <summary>
        /// <lang><zh-CN>页面提示。</zh-CN><en>Page-level message.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// <lang><zh-CN>当前有效绑定标识。</zh-CN><en>Current active binding identifier.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField ActiveBindingId;

        /// <summary>
        /// <lang><zh-CN>当前绑定说明。</zh-CN><en>Current binding summary.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label CurrentBindingText;

        /// <summary>
        /// <lang><zh-CN>门户用户标识输入。</zh-CN><en>Portal user-id input.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox UserIdTextBox;

        /// <summary>
        /// <lang><zh-CN>门户用户摘要。</zh-CN><en>Portal user summary.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UserSummaryText;

        /// <summary>
        /// <lang><zh-CN>员工号输入。</zh-CN><en>Employee-code input.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmployeeCodeTextBox;

        /// <summary>
        /// <lang><zh-CN>员工摘要。</zh-CN><en>Employee summary.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.Label EmployeeSummaryText;

        /// <summary>
        /// <lang><zh-CN>绑定或解绑原因。</zh-CN><en>Binding or unbinding reason.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ReasonTextBox;

        /// <summary>
        /// <lang><zh-CN>建立绑定按钮。</zh-CN><en>Create-binding button.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton BindButton;

        /// <summary>
        /// <lang><zh-CN>结束绑定按钮。</zh-CN><en>End-binding button.</en></lang>
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton EndBindingButton;
    }
}
