//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class Users
    {

        /// <summary><lang><zh-CN>显示用户管理模块标题的门户标题控件。</zh-CN><en>Portal title control that displays the user-management module title.</en></lang></summary>
        protected global::ASPNET.StarterKit.Portal.DesktopModuleTitle Title1;

        /// <summary><lang><zh-CN>显示用户管理操作结果或失败原因的消息文字。</zh-CN><en>Message text for user-management operation results or failure reasons.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Literal Message;

        /// <summary><lang><zh-CN>供管理员选择目标用户的下拉列表。</zh-CN><en>Drop-down list from which an administrator selects the target user.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList ddl_AllUsers;

        /// <summary><lang><zh-CN>打开所选用户编辑流程的命令按钮。</zh-CN><en>Command button that opens the edit flow for the selected user.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton btn_EditUser;

        /// <summary><lang><zh-CN>删除所选用户的命令按钮；权限和确认边界由页面逻辑决定。</zh-CN><en>Command button that deletes the selected user; authorization and confirmation boundaries are defined by page logic.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton btn_DeleteUser;

        /// <summary><lang><zh-CN>打开新增用户流程的命令按钮。</zh-CN><en>Command button that opens the add-user flow.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton btn_AddUser;
    }
}
