//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class UserEmployeeBindingEdit
    {
        /// <summary>中文：返回用户管理页链接。English: Link back to user administration.</summary>
        protected global::System.Web.UI.WebControls.HyperLink ManageUserLink;

        /// <summary>中文：页面提示。English: Page-level message.</summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>中文：当前有效绑定标识。English: Current active binding identifier.</summary>
        protected global::System.Web.UI.WebControls.HiddenField ActiveBindingId;

        /// <summary>中文：当前绑定说明。English: Current binding summary.</summary>
        protected global::System.Web.UI.WebControls.Label CurrentBindingText;

        /// <summary>中文：门户用户标识输入。English: Portal user-id input.</summary>
        protected global::System.Web.UI.WebControls.TextBox UserIdTextBox;

        /// <summary>中文：门户用户摘要。English: Portal user summary.</summary>
        protected global::System.Web.UI.WebControls.Label UserSummaryText;

        /// <summary>中文：员工号输入。English: Employee-code input.</summary>
        protected global::System.Web.UI.WebControls.TextBox EmployeeCodeTextBox;

        /// <summary>中文：员工摘要。English: Employee summary.</summary>
        protected global::System.Web.UI.WebControls.Label EmployeeSummaryText;

        /// <summary>中文：绑定或解绑原因。English: Binding or unbinding reason.</summary>
        protected global::System.Web.UI.WebControls.TextBox ReasonTextBox;

        /// <summary>中文：建立绑定按钮。English: Create-binding button.</summary>
        protected global::System.Web.UI.WebControls.LinkButton BindButton;

        /// <summary>中文：结束绑定按钮。English: End-binding button.</summary>
        protected global::System.Web.UI.WebControls.LinkButton EndBindingButton;
    }
}
