//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class WorkItems
    {
        /// <summary><lang><zh-CN>显示待办查询操作状态消息。</zh-CN><en>Displays the work-item query operation status.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary><lang><zh-CN>按待办状态筛选列表。</zh-CN><en>Filters the list by work-item status.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList StatusFilterList;

        /// <summary><lang><zh-CN>提交待办状态筛选查询的按钮。</zh-CN><en>Button that submits the work-item status filter query.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton SearchButton;

        /// <summary><lang><zh-CN>显示待办查询结果摘要的标签。</zh-CN><en>Label that displays the work-item result summary.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ResultLabel;

        /// <summary><lang><zh-CN>绑定待办结果行的 Repeater。</zh-CN><en>Repeater bound to work-item result rows.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater WorkItemsRepeater;
    }
}
