<%@ Page
    Language="c#"
    CodeBehind="WorkItems.aspx.cs"
    AutoEventWireup="True"
    Inherits="ASPNET.StarterKit.Portal.WorkItems"
    MasterPageFile="~/Default.master" %>

<%--
  <lang>
    <zh-CN>P12.3 轻量待办后台入口：第一版只读集中查看，不提供流程设计器或转办；P21.3 起同时承接协同事项待办投影。</zh-CN>
    <en>P12.3 lightweight work-item Admin entry: the first version is a read-only central view without workflow designer or reassignment; P21.3 also projects collaboration-item work entries here.</en>
  </lang>
--%>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="portal-admin-page portal-admin-work-items">
        <div class="portal-admin-header">
            <div class="portal-admin-heading">
                <h1 class="Head portal-admin-title">Work Items</h1>
                <p class="Normal portal-admin-subtitle">Review lightweight business work items and their current handling state.</p>
            </div>
            <div class="portal-admin-actions">
                <a class="CommandButton" href="EmployeeProfileCorrectionRequests.aspx">Correction Requests</a>
                <a class="CommandButton" href="CollaborationItems.aspx">Collaboration Items</a>
                <a class="CommandButton" href="OperationAudits.aspx">Operation Audits</a>
            </div>
        </div>

        <asp:Label ID="MessageLabel" CssClass="NormalRed portal-status-line" EnableViewState="false" runat="server" />

        <div class="portal-admin-section portal-filter-panel">
            <div class="portal-filter-grid">
                <div class="portal-filter-field">
                    <span class="SubHead portal-filter-label">Status</span>
                    <asp:DropDownList ID="StatusFilterList" CssClass="NormalTextBox portal-filter-input" runat="server" />
                </div>
                <div class="portal-filter-actions">
                    <asp:LinkButton
                        ID="SearchButton"
                        Text="Search"
                        CssClass="CommandButton"
                        CausesValidation="False"
                        OnClick="SearchButton_Click"
                        runat="server" />
                </div>
            </div>
        </div>

        <div class="portal-status-strip">
            <div class="Normal portal-status-line">
                <asp:Label ID="ResultLabel" runat="server" />
            </div>
        </div>

        <div class="portal-admin-section">
            <div class="portal-section-header">
                <h2 class="Head portal-section-title">Current Work Items</h2>
            </div>
            <div class="portal-table-wrap">
                <%--
                <lang>
                  <zh-CN>待办数据由已通过权限门禁的 code-behind 绑定；此标记层不直接查询或拼接业务数据。空集合和 schema 不可用状态由后端清空 Repeater 并显示受控提示。</zh-CN>
                  <en>Work-item data is bound by code-behind after the permission gate; this markup layer neither queries nor concatenates business data directly. The backend clears the Repeater and shows controlled messaging for empty collections and unavailable schema.</en>
                </lang>
                --%>
                <asp:Repeater ID="WorkItemsRepeater" runat="server">
                    <HeaderTemplate>
                        <table class="portal-data-table" width="100%" cellspacing="0" cellpadding="0" border="0">
                            <tr>
                                <th scope="col" width="70" class="SubHead">ID</th>
                                <th scope="col" width="95" class="SubHead">Status</th>
                                <th scope="col" width="180" class="SubHead">Business</th>
                                <th scope="col" class="SubHead">Title / Summary</th>
                                <th scope="col" width="190" class="SubHead">Assigned To</th>
                                <th scope="col" width="145" class="SubHead">Created UTC</th>
                                <th scope="col" width="145" class="SubHead">Completed UTC</th>
                            </tr>
                    </HeaderTemplate>
                    <%--
                    <lang>
                      <zh-CN>展示值使用 `<%#:` 编码绑定，避免待办标题、摘要和分派文字作为原始 HTML 输出。业务入口只绑定 code-behind 生成的固定本地白名单 URL；不展示或拼接 BusinessId，未知类型已在服务器映射到占位页。</zh-CN>
                      <en>Display values use `<%#:` encoded binding so work-item title, summary, and assignment text are not emitted as raw HTML. The business entry binds only the fixed local allowlisted URL generated by code-behind; it neither displays nor concatenates BusinessId, and unknown kinds are server-mapped to the placeholder page.</en>
                    </lang>
                    --%>
                    <ItemTemplate>
                            <tr class="Normal">
                                <td><%#: Eval("WorkItemId") %></td>
                                <td><%#: Eval("WorkItemStatus") %></td>
                                <td>
                                    <div class="portal-value-stack">
                                        <div><%#: Eval("BusinessKind") %></div>
                                        <div><a class="CommandButton" href='<%#: Eval("BusinessUrl") %>'>Open Source</a></div>
                                    </div>
                                </td>
                                <td>
                                    <div class="portal-value-stack">
                                        <div class="SubHead"><%#: Eval("Title") %></div>
                                        <div><%#: Eval("Summary") %></div>
                                    </div>
                                </td>
                                <td><%#: Eval("AssignedText") %></td>
                                <td><%#: Eval("CreatedUtcText") %></td>
                                <td><%#: Eval("CompletedUtcText") %></td>
                            </tr>
                    </ItemTemplate>
                    <FooterTemplate>
                        </table>
                    </FooterTemplate>
                </asp:Repeater>
            </div>
        </div>
    </div>
</asp:Content>
