//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class EmployeeProfileConfirm
    {
        /// <summary><lang><zh-CN>显示资料确认流程的状态消息。</zh-CN><en>Displays the status message for the profile-confirmation flow.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary><lang><zh-CN>承载当前员工资料和确认操作的面板。</zh-CN><en>Panel that contains the current employee profile and confirmation action.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel ProfilePanel;

        /// <summary><lang><zh-CN>显示员工号的只读标签。</zh-CN><en>Read-only label that displays the employee code.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label EmployeeCodeLabel;

        /// <summary><lang><zh-CN>显示员工显示名的只读标签。</zh-CN><en>Read-only label that displays the employee display name.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label DisplayNameLabel;

        /// <summary><lang><zh-CN>显示员工偏好称呼的只读标签。</zh-CN><en>Read-only label that displays the employee preferred name.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label PreferredNameLabel;

        /// <summary><lang><zh-CN>显示员工工作邮箱的只读标签。</zh-CN><en>Read-only label that displays the employee work email.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label WorkEmailLabel;

        /// <summary><lang><zh-CN>显示员工组织名称的只读标签。</zh-CN><en>Read-only label that displays the employee organization.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label OrganizationLabel;

        /// <summary><lang><zh-CN>显示员工在职状态的只读标签。</zh-CN><en>Read-only label that displays the employee employment status.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label EmploymentStatusLabel;

        /// <summary><lang><zh-CN>显示资料上次确认 UTC 时间的只读标签。</zh-CN><en>Read-only label that displays the last profile-confirmation time in UTC.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label LastConfirmedLabel;

        /// <summary><lang><zh-CN>提交当前员工资料确认动作的按钮。</zh-CN><en>Button that submits confirmation of the current employee profile.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Button ConfirmButton;
    }
}
