//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的容器文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added container documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal {

    /// <summary>
    /// <lang>
    ///   <zh-CN>门户根入口页的 Designer partial 容器；页面不声明服务器控件，因此当前没有生成字段。</zh-CN>
    ///   <en>Designer partial container for the portal root endpoint; the page declares no server controls, so no generated fields are present.</en>
    /// </lang>
    /// </summary>
    public partial class CDefault {
    }
}
