//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class DesktopDefault
    {

        /// <summary><lang><zh-CN>承载门户左侧模块区域的服务端容器。</zh-CN><en>Server-side container for the portal's left module region.</en></lang></summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl LeftPane;

        /// <summary><lang><zh-CN>承载门户主内容模块区域的服务端容器。</zh-CN><en>Server-side container for the portal's main content-module region.</en></lang></summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ContentPane;

        /// <summary><lang><zh-CN>承载门户右侧模块区域的服务端容器。</zh-CN><en>Server-side container for the portal's right module region.</en></lang></summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl RightPane;
    }
}
