//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class DesktopModuleTitle
    {

        /// <summary><lang><zh-CN>显示模块标题文本的标签。</zh-CN><en>Label that displays the module title text.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ModuleTitle;

        /// <summary><lang><zh-CN>承载模块级操作入口的面板。</zh-CN><en>Panel that contains module-level action entries.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel ModuleActions;

        /// <summary><lang><zh-CN>指向当前模块编辑入口的链接。</zh-CN><en>Link to the current module's edit entry point.</en></lang></summary>
        protected global::System.Web.UI.WebControls.HyperLink EditButton;
    }
}
