//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{


    public partial class DesktopPortalBanner
    {

        /// <summary><lang><zh-CN>显示门户欢迎消息的标签。</zh-CN><en>Label that displays the portal welcome message.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label WelcomeMessage;

        /// <summary><lang><zh-CN>显示当前站点名称的标签。</zh-CN><en>Label that displays the current site name.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label SiteName;

        /// <summary><lang><zh-CN>绑定门户导航页签集合的 DataList。</zh-CN><en>DataList bound to the portal navigation-tab collection.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DataList Tabs;
    }
}
