using System;
using System.Web.UI;

namespace ASPNET.StarterKit.Portal
{
    /// <summary>
    /// Shows the generic diagnostics error page without depending on portal database context.
    /// 显示通用诊断错误页，不依赖门户数据库上下文。
    /// </summary>
    public partial class GenericErrorPage : Page
    {
        /// <summary>
        /// Encoded diagnostics event id rendered by the generic error page.
        /// 通用错误页输出的已编码诊断事件编号。
        /// </summary>
        protected string EventIdText { get; private set; }

        /// <summary>
        /// Loads the diagnostics event id generated by <see cref="PortalDiagnostics"/>.
        /// 加载由 <see cref="PortalDiagnostics"/> 生成的诊断事件编号。
        /// </summary>
        protected void Page_Load(object sender, EventArgs e)
        {
            string eventId = Request.QueryString["id"] ?? Context.Items["PortalDiagnostics.EventId"] as string;
            EventIdText = Server.HtmlEncode(string.IsNullOrWhiteSpace(eventId) ? "未提供" : eventId);
        }
    }
}
