using System;
using System.Web.UI;

namespace ASPNET.StarterKit.Portal
{
    /// <summary>
    /// <lang>
    ///   <zh-CN>显示通用诊断错误页，不依赖门户数据库上下文。</zh-CN>
    ///   <en>Shows the generic diagnostics error page without depending on portal database context.</en>
    /// </lang>
    /// </summary>
    public partial class GenericErrorPage : Page
    {
        /// <summary>
        /// <l>
        ///   <zh-CN>通用错误页输出的已编码诊断事件编号。</zh-CN>
        ///   <en>Encoded diagnostics event id rendered by the generic error page.</en>
        /// </l>
        /// </summary>
        protected string EventIdText { get; private set; }

        /// <summary>
        /// <lang>
        ///   <zh-CN>加载并严格校验由 <see cref="PortalDiagnostics"/> 生成的诊断事件编号。</zh-CN>
        ///   <en>Loads and strictly validates the diagnostics event id generated by <see cref="PortalDiagnostics"/>.</en>
        /// </lang>
        /// </summary>
        /// <param name="sender">
        /// <l>
        ///   <zh-CN>Web Forms 生命周期事件来源；本页不依赖该值。</zh-CN>
        ///   <en>Web Forms lifecycle event source; this page does not depend on the value.</en>
        /// </l>
        /// </param>
        /// <param name="e">
        /// <l>
        ///   <zh-CN>事件参数；保留用于匹配 Web Forms 生命周期签名。</zh-CN>
        ///   <en>Event arguments retained to match the Web Forms lifecycle signature.</en>
        /// </l>
        /// </param>
        protected void Page_Load(object sender, EventArgs e)
        {
            string eventId = Request.QueryString["id"] ?? Context.Items["PortalDiagnostics.EventId"] as string;
            EventIdText = Server.HtmlEncode(
                PortalDiagnosticQueryService.IsValidEventId(eventId) ? eventId : "未提供");
        }
    }
}
