using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace ASPNET.StarterKit.Portal
{
    /// <summary>
    /// 受限的结构化诊断日志查询服务。
    /// Restricted structured diagnostic-log query service.
    /// </summary>
    /// <remarks>
    /// 只扫描由 <see cref="PortalDiagnostics"/> 生成的 NDJSON 文件；不接受文件系统路径、
    /// 不提供下载，并通过日期、文件和条目上限避免管理员页面触发无限扫描。
    /// Only scans NDJSON files generated by <see cref="PortalDiagnostics"/>; it accepts no
    /// filesystem paths, exposes no download capability, and caps date, file, and entry scans.
    /// </remarks>
    public static class PortalDiagnosticQueryService
    {
        private const int DefaultPageSize = 50;
        private const int MaximumPageSize = 50;
        private const int MaximumPage = 99;
        private const int MaximumQueryDays = 31;
        private const int MaximumScannedFiles = 128;
        private const int MaximumScannedEntries = 10000;

        private static readonly Regex EventIdPattern = new Regex(
            @"^(?<date>\d{8})\d{9}-[0-9a-f]{8}$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);

        private static readonly Regex FileNamePattern = new Regex(
            @"^portal-(?<date>\d{8})-(?<sequence>\d{3})\.jsonl$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);

        /// <summary>
        /// 中文：验证是否为当前运行时生成的诊断事件编号格式。
        ///
        /// English: Verifies whether a value has the diagnostics event-id format generated by the current runtime.
        /// </summary>
        /// <param name="eventId">中文：待验证的事件编号。English: Event id to validate.</param>
        /// <returns>中文：格式与日期部分均有效时为 <c>true</c>。English: <c>true</c> when both the format and date portion are valid.</returns>
        public static bool IsValidEventId(string eventId)
        {
            DateTime eventDate;
            return TryGetEventDate(eventId, out eventDate);
        }

        /// <summary>
        /// 查询符合受限条件的诊断日志。
        /// Queries diagnostic logs that satisfy restricted criteria.
        /// </summary>
        /// <param name="query">日期、级别、分类和分页等受限查询条件。Restricted date, level, category, and paging criteria.</param>
        /// <returns>当前页诊断记录及截断状态。Current-page diagnostics records and truncation state.</returns>
        public static PortalDiagnosticQueryResult Query(PortalDiagnosticQuery query)
        {
            PortalDiagnosticQuery normalized = NormalizeQuery(query);
            var matches = new List<PortalDiagnosticEntry>();
            bool wasTruncated = false;
            int scannedEntries = 0;

            string logDirectory = PortalDiagnostics.ResolveLogDirectory();
            if (!Directory.Exists(logDirectory))
            {
                return new PortalDiagnosticQueryResult(matches, false, false);
            }

            foreach (FileInfo logFile in GetLogFiles(logDirectory, normalized.StartUtc, normalized.EndUtcExclusive))
            {
                try
                {
                    foreach (string line in File.ReadLines(logFile.FullName))
                    {
                        scannedEntries++;
                        if (scannedEntries > MaximumScannedEntries)
                        {
                            wasTruncated = true;
                            break;
                        }

                        PortalDiagnosticEntry entry = ParseEntry(line, logFile.Name);
                        if (entry != null && Matches(entry, normalized))
                        {
                            matches.Add(entry);
                        }
                    }
                }
                catch (Exception exception)
                {
                    Trace.TraceWarning(
                        "Portal diagnostic query skipped file '{0}'. Error={1}",
                        logFile.Name,
                        PortalDiagnosticSanitizer.SanitizeAndTruncate(exception.Message, 500));
                }

                if (wasTruncated)
                {
                    break;
                }
            }

            matches = matches
                .OrderByDescending(item => item.UtcTime)
                .ThenByDescending(item => item.EventId, StringComparer.Ordinal)
                .ToList();

            int skip = normalized.Page * normalized.PageSize;
            bool hasMore = matches.Count > skip + normalized.PageSize;
            IList<PortalDiagnosticEntry> page = skip >= matches.Count
                ? new List<PortalDiagnosticEntry>()
                : matches.Skip(skip).Take(normalized.PageSize).ToList();

            return new PortalDiagnosticQueryResult(page, hasMore, wasTruncated);
        }

        /// <summary>
        /// 按事件编号读取一条结构化诊断日志。
        /// Finds one structured diagnostic entry by event id.
        /// </summary>
        /// <param name="eventId">系统生成的诊断事件编号。System-generated diagnostics event id.</param>
        /// <returns>匹配的已净化事件；找不到或编号非法时返回 <c>null</c>。The sanitized event, or <c>null</c> when not found or invalid.</returns>
        public static PortalDiagnosticEntry FindByEventId(string eventId)
        {
            DateTime eventDate;
            if (!TryGetEventDate(eventId, out eventDate))
            {
                return null;
            }

            string logDirectory = PortalDiagnostics.ResolveLogDirectory();
            if (!Directory.Exists(logDirectory))
            {
                return null;
            }

            int scannedEntries = 0;
            foreach (FileInfo logFile in GetLogFiles(logDirectory, eventDate, eventDate.AddDays(1)))
            {
                try
                {
                    foreach (string line in File.ReadLines(logFile.FullName))
                    {
                        scannedEntries++;
                        if (scannedEntries > MaximumScannedEntries)
                        {
                            Trace.TraceWarning(
                                "Portal diagnostic detail reached scan cap of {0} entries for event '{1}'.",
                                MaximumScannedEntries,
                                eventId);
                            return null;
                        }

                        PortalDiagnosticEntry entry = ParseEntry(line, logFile.Name);
                        if (entry != null && string.Equals(entry.EventId, eventId, StringComparison.Ordinal))
                        {
                            return entry;
                        }
                    }
                }
                catch (Exception exception)
                {
                    Trace.TraceWarning(
                        "Portal diagnostic detail skipped file '{0}'. Error={1}",
                        logFile.Name,
                        PortalDiagnosticSanitizer.SanitizeAndTruncate(exception.Message, 500));
                }
            }

            return null;
        }

        private static PortalDiagnosticQuery NormalizeQuery(PortalDiagnosticQuery query)
        {
            DateTime nowUtc = DateTime.UtcNow.Date;
            DateTime startUtc = query == null || query.StartUtc == DateTime.MinValue
                ? nowUtc.AddDays(-6)
                : query.StartUtc.Date;
            DateTime endUtcExclusive = query == null || query.EndUtcExclusive == DateTime.MinValue
                ? nowUtc.AddDays(1)
                : query.EndUtcExclusive.Date;

            if (endUtcExclusive <= startUtc)
            {
                endUtcExclusive = startUtc.AddDays(1);
            }

            if ((endUtcExclusive - startUtc).TotalDays > MaximumQueryDays)
            {
                endUtcExclusive = startUtc.AddDays(MaximumQueryDays);
            }

            return new PortalDiagnosticQuery
            {
                StartUtc = DateTime.SpecifyKind(startUtc, DateTimeKind.Utc),
                EndUtcExclusive = DateTime.SpecifyKind(endUtcExclusive, DateTimeKind.Utc),
                Level = NormalizeFilter(query == null ? null : query.Level, 20),
                Category = NormalizeFilter(query == null ? null : query.Category, 80),
                EventId = NormalizeFilter(query == null ? null : query.EventId, 64),
                Page = Math.Max(0, Math.Min(query == null ? 0 : query.Page, MaximumPage)),
                PageSize = Math.Max(1, Math.Min(query == null || query.PageSize <= 0 ? DefaultPageSize : query.PageSize, MaximumPageSize))
            };
        }

        private static IEnumerable<FileInfo> GetLogFiles(string logDirectory, DateTime startUtc, DateTime endUtcExclusive)
        {
            var files = new List<FileInfo>();
            foreach (string path in Directory.EnumerateFiles(logDirectory, "portal-*.jsonl", SearchOption.TopDirectoryOnly))
            {
                DateTime fileDate;
                int sequence;
                if (!TryGetFileParts(Path.GetFileName(path), out fileDate, out sequence) ||
                    fileDate < startUtc.Date ||
                    fileDate >= endUtcExclusive.Date)
                {
                    continue;
                }

                files.Add(new FileInfo(path));
            }

            return files
                .OrderByDescending(item => item.Name, StringComparer.OrdinalIgnoreCase)
                .Take(MaximumScannedFiles)
                .ToList();
        }

        private static PortalDiagnosticEntry ParseEntry(string line, string fileName)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                return null;
            }

            try
            {
                return JsonConvert.DeserializeObject<PortalDiagnosticEntry>(line);
            }
            catch (Exception exception)
            {
                Trace.TraceWarning(
                    "Portal diagnostic query skipped malformed entry in '{0}'. Error={1}",
                    fileName,
                    PortalDiagnosticSanitizer.SanitizeAndTruncate(exception.Message, 300));
                return null;
            }
        }

        private static bool Matches(PortalDiagnosticEntry entry, PortalDiagnosticQuery query)
        {
            if (entry.UtcTime < query.StartUtc || entry.UtcTime >= query.EndUtcExclusive)
            {
                return false;
            }

            if (!string.IsNullOrEmpty(query.Level) && !string.Equals(entry.Level, query.Level, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            if (!string.IsNullOrEmpty(query.Category) && !string.Equals(entry.Category, query.Category, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            return string.IsNullOrEmpty(query.EventId) ||
                   string.Equals(entry.EventId, query.EventId, StringComparison.Ordinal);
        }

        private static bool TryGetEventDate(string eventId, out DateTime eventDate)
        {
            eventDate = DateTime.MinValue;
            Match match = EventIdPattern.Match(eventId ?? string.Empty);
            if (!match.Success)
            {
                return false;
            }

            return DateTime.TryParseExact(
                match.Groups["date"].Value,
                "yyyyMMdd",
                CultureInfo.InvariantCulture,
                DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                out eventDate);
        }

        private static bool TryGetFileParts(string fileName, out DateTime fileDate, out int sequence)
        {
            fileDate = DateTime.MinValue;
            sequence = 0;
            Match match = FileNamePattern.Match(fileName ?? string.Empty);
            if (!match.Success ||
                !DateTime.TryParseExact(
                    match.Groups["date"].Value,
                    "yyyyMMdd",
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                    out fileDate))
            {
                return false;
            }

            return int.TryParse(match.Groups["sequence"].Value, NumberStyles.None, CultureInfo.InvariantCulture, out sequence);
        }

        private static string NormalizeFilter(string value, int maximumLength)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return string.Empty;
            }

            string normalized = value.Trim();
            return normalized.Substring(0, Math.Min(normalized.Length, maximumLength));
        }
    }
}
