using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;

namespace ASPNET.StarterKit.Portal
{
    /// <summary>
    /// <lang>
    ///   <zh-CN>受限的结构化诊断日志查询服务。</zh-CN>
    ///   <en>Restricted structured diagnostic-log query service.</en>
    /// </lang>
    /// </summary>
    /// <remarks>
    /// <lang>
    ///   <zh-CN>只扫描由 <see cref="PortalDiagnostics"/> 生成的 NDJSON 文件；不接受文件系统路径，不提供下载，并通过日期、文件和条目上限避免管理员页面触发无限扫描。</zh-CN>
    ///   <en>Only scans NDJSON files generated by <see cref="PortalDiagnostics"/>; it accepts no filesystem paths, exposes no download capability, and caps date, file, and entry scans.</en>
    /// </lang>
    /// </remarks>
    public static class PortalDiagnosticQueryService
    {
        private const int DefaultPageSize = 50;
        private const int MaximumPageSize = 50;
        private const int MaximumPage = 99;
        private const int MaximumQueryDays = 31;
        private const int MaximumScannedFiles = 128;
        private const int MaximumScannedEntries = 10000;

        private static readonly Regex EventIdPattern = new Regex(
            @"^(?<date>\d{8})\d{9}-[0-9a-f]{8}$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);

        private static readonly Regex FileNamePattern = new Regex(
            @"^portal-(?<date>\d{8})-(?<sequence>\d{3})\.jsonl$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);

        /// <summary>
        /// <lang>
        ///   <zh-CN>验证是否为当前运行时生成的诊断事件编号格式。</zh-CN>
        ///   <en>Verifies whether a value has the diagnostics event-id format generated by the current runtime.</en>
        /// </lang>
        /// </summary>
        /// <param name="eventId">
        /// <l>
        ///   <zh-CN>待验证的事件编号。</zh-CN>
        ///   <en>Event id to validate.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>格式与日期部分均有效时为 <c>true</c>。</zh-CN>
        ///   <en><c>true</c> when both the format and date portion are valid.</en>
        /// </l>
        /// </returns>
        public static bool IsValidEventId(string eventId)
        {
            DateTime eventDate;
            return TryGetEventDate(eventId, out eventDate);
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查询符合受限条件的诊断日志。</zh-CN>
        ///   <en>Queries diagnostic logs that satisfy restricted criteria.</en>
        /// </lang>
        /// </summary>
        /// <remarks>
        /// <lang>
        ///   <zh-CN>查询先归一化日期和分页，再按文件名日期筛选日志文件。坏行或坏文件不会阻断整个后台页面，而是写入受净化的 Trace 警告。</zh-CN>
        ///   <en>The query first normalizes date and paging values, then filters log files by the date embedded in their names. Malformed lines or unreadable files do not block the whole administration page; they emit sanitized Trace warnings instead.</en>
        /// </lang>
        /// </remarks>
        /// <param name="query">
        /// <l>
        ///   <zh-CN>日期、级别、分类和分页等受限查询条件。</zh-CN>
        ///   <en>Restricted date, level, category, and paging criteria.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>当前页诊断记录及截断状态。</zh-CN>
        ///   <en>Current-page diagnostics records and truncation state.</en>
        /// </l>
        /// </returns>
        public static PortalDiagnosticQueryResult Query(PortalDiagnosticQuery query)
        {
            PortalDiagnosticQuery normalized = NormalizeQuery(query);
            var matches = new List<PortalDiagnosticEntry>();
            bool wasTruncated = false;
            int scannedEntries = 0;

            string logDirectory = PortalDiagnostics.ResolveLogDirectory();
            if (!Directory.Exists(logDirectory))
            {
                return new PortalDiagnosticQueryResult(matches, false, false);
            }

            foreach (FileInfo logFile in GetLogFiles(logDirectory, normalized.StartUtc, normalized.EndUtcExclusive))
            {
                try
                {
                    foreach (string line in File.ReadLines(logFile.FullName))
                    {
                        scannedEntries++;
                        if (scannedEntries > MaximumScannedEntries)
                        {
                            wasTruncated = true;
                            break;
                        }

                        PortalDiagnosticEntry entry = ParseEntry(line, logFile.Name);
                        if (entry != null && Matches(entry, normalized))
                        {
                            matches.Add(entry);
                        }
                    }
                }
                catch (Exception exception)
                {
                    Trace.TraceWarning(
                        "Portal diagnostic query skipped file '{0}'. Error={1}",
                        logFile.Name,
                        PortalDiagnosticSanitizer.SanitizeAndTruncate(exception.Message, 500));
                }

                if (wasTruncated)
                {
                    break;
                }
            }

            matches = matches
                .OrderByDescending(item => item.UtcTime)
                .ThenByDescending(item => item.EventId, StringComparer.Ordinal)
                .ToList();

            int skip = normalized.Page * normalized.PageSize;
            bool hasMore = matches.Count > skip + normalized.PageSize;
            IList<PortalDiagnosticEntry> page = skip >= matches.Count
                ? new List<PortalDiagnosticEntry>()
                : matches.Skip(skip).Take(normalized.PageSize).ToList();

            return new PortalDiagnosticQueryResult(page, hasMore, wasTruncated);
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>按事件编号读取一条结构化诊断日志。</zh-CN>
        ///   <en>Finds one structured diagnostic entry by event id.</en>
        /// </lang>
        /// </summary>
        /// <remarks>
        /// <lang>
        ///   <zh-CN>事件编号内含日期，因此详情查询只扫描对应日期的日志文件；编号非法、目录缺失或扫描超限都按未找到处理。</zh-CN>
        ///   <en>The event id contains the date, so detail lookup only scans log files for that date; invalid ids, missing directories, or scan caps are treated as not found.</en>
        /// </lang>
        /// </remarks>
        /// <param name="eventId">
        /// <l>
        ///   <zh-CN>系统生成的诊断事件编号。</zh-CN>
        ///   <en>System-generated diagnostics event id.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>匹配的已净化事件；找不到或编号非法时返回 <c>null</c>。</zh-CN>
        ///   <en>The sanitized event, or <c>null</c> when not found or invalid.</en>
        /// </l>
        /// </returns>
        public static PortalDiagnosticEntry FindByEventId(string eventId)
        {
            DateTime eventDate;
            if (!TryGetEventDate(eventId, out eventDate))
            {
                return null;
            }

            string logDirectory = PortalDiagnostics.ResolveLogDirectory();
            if (!Directory.Exists(logDirectory))
            {
                return null;
            }

            int scannedEntries = 0;
            foreach (FileInfo logFile in GetLogFiles(logDirectory, eventDate, eventDate.AddDays(1)))
            {
                try
                {
                    foreach (string line in File.ReadLines(logFile.FullName))
                    {
                        scannedEntries++;
                        if (scannedEntries > MaximumScannedEntries)
                        {
                            Trace.TraceWarning(
                                "Portal diagnostic detail reached scan cap of {0} entries for event '{1}'.",
                                MaximumScannedEntries,
                                eventId);
                            return null;
                        }

                        PortalDiagnosticEntry entry = ParseEntry(line, logFile.Name);
                        if (entry != null && string.Equals(entry.EventId, eventId, StringComparison.Ordinal))
                        {
                            return entry;
                        }
                    }
                }
                catch (Exception exception)
                {
                    Trace.TraceWarning(
                        "Portal diagnostic detail skipped file '{0}'. Error={1}",
                        logFile.Name,
                        PortalDiagnosticSanitizer.SanitizeAndTruncate(exception.Message, 500));
                }
            }

            return null;
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>归一化诊断查询条件并限制扫描范围。</zh-CN>
        ///   <en>Normalizes diagnostic query criteria and constrains the scan scope.</en>
        /// </lang>
        /// </summary>
        /// <param name="query">
        /// <l>
        ///   <zh-CN>来自后台页面的原始查询条件。</zh-CN>
        ///   <en>The raw query criteria from the administration page.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>日期、分页和过滤字段均已裁剪的查询对象。</zh-CN>
        ///   <en>A query object with date, paging, and filter fields clamped.</en>
        /// </l>
        /// </returns>
        private static PortalDiagnosticQuery NormalizeQuery(PortalDiagnosticQuery query)
        {
            DateTime nowUtc = DateTime.UtcNow.Date;
            DateTime startUtc = query == null || query.StartUtc == DateTime.MinValue
                ? nowUtc.AddDays(-6)
                : query.StartUtc.Date;
            DateTime endUtcExclusive = query == null || query.EndUtcExclusive == DateTime.MinValue
                ? nowUtc.AddDays(1)
                : query.EndUtcExclusive.Date;

            if (endUtcExclusive <= startUtc)
            {
                endUtcExclusive = startUtc.AddDays(1);
            }

            if ((endUtcExclusive - startUtc).TotalDays > MaximumQueryDays)
            {
                endUtcExclusive = startUtc.AddDays(MaximumQueryDays);
            }

            return new PortalDiagnosticQuery
            {
                StartUtc = DateTime.SpecifyKind(startUtc, DateTimeKind.Utc),
                EndUtcExclusive = DateTime.SpecifyKind(endUtcExclusive, DateTimeKind.Utc),
                Level = NormalizeFilter(query == null ? null : query.Level, 20),
                Category = NormalizeFilter(query == null ? null : query.Category, 80),
                EventId = NormalizeFilter(query == null ? null : query.EventId, 64),
                Page = Math.Max(0, Math.Min(query == null ? 0 : query.Page, MaximumPage)),
                PageSize = Math.Max(1, Math.Min(query == null || query.PageSize <= 0 ? DefaultPageSize : query.PageSize, MaximumPageSize))
            };
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>按受控文件名模式和日期范围枚举候选日志文件。</zh-CN>
        ///   <en>Enumerates candidate log files by controlled file-name pattern and date range.</en>
        /// </lang>
        /// </summary>
        /// <param name="logDirectory">
        /// <l>
        ///   <zh-CN>结构化诊断日志目录。</zh-CN>
        ///   <en>The structured diagnostics log directory.</en>
        /// </l>
        /// </param>
        /// <param name="startUtc">
        /// <l>
        ///   <zh-CN>查询起始 UTC 日期。</zh-CN>
        ///   <en>The query start UTC date.</en>
        /// </l>
        /// </param>
        /// <param name="endUtcExclusive">
        /// <l>
        ///   <zh-CN>查询结束 UTC 日期，不包含当天。</zh-CN>
        ///   <en>The exclusive query end UTC date.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>按文件名倒序排列且数量受限的日志文件集合。</zh-CN>
        ///   <en>Log files ordered by file name descending and capped by count.</en>
        /// </l>
        /// </returns>
        private static IEnumerable<FileInfo> GetLogFiles(string logDirectory, DateTime startUtc, DateTime endUtcExclusive)
        {
            var files = new List<FileInfo>();
            foreach (string path in Directory.EnumerateFiles(logDirectory, "portal-*.jsonl", SearchOption.TopDirectoryOnly))
            {
                DateTime fileDate;
                int sequence;
                if (!TryGetFileParts(Path.GetFileName(path), out fileDate, out sequence) ||
                    fileDate < startUtc.Date ||
                    fileDate >= endUtcExclusive.Date)
                {
                    continue;
                }

                files.Add(new FileInfo(path));
            }

            return files
                .OrderByDescending(item => item.Name, StringComparer.OrdinalIgnoreCase)
                .Take(MaximumScannedFiles)
                .ToList();
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>解析单行 NDJSON 诊断事件。</zh-CN>
        ///   <en>Parses one NDJSON diagnostics event line.</en>
        /// </lang>
        /// </summary>
        /// <param name="line">
        /// <l>
        ///   <zh-CN>日志文件中的原始单行文本。</zh-CN>
        ///   <en>The raw single line from the log file.</en>
        /// </l>
        /// </param>
        /// <param name="fileName">
        /// <l>
        ///   <zh-CN>用于 Trace 警告定位的日志文件名。</zh-CN>
        ///   <en>The log file name used to locate Trace warnings.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>解析成功的诊断事件；空行或格式错误时返回 <c>null</c>。</zh-CN>
        ///   <en>The parsed diagnostics event, or <c>null</c> for empty or malformed lines.</en>
        /// </l>
        /// </returns>
        private static PortalDiagnosticEntry ParseEntry(string line, string fileName)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                return null;
            }

            try
            {
                return JsonConvert.DeserializeObject<PortalDiagnosticEntry>(line);
            }
            catch (Exception exception)
            {
                Trace.TraceWarning(
                    "Portal diagnostic query skipped malformed entry in '{0}'. Error={1}",
                    fileName,
                    PortalDiagnosticSanitizer.SanitizeAndTruncate(exception.Message, 300));
                return null;
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>判断诊断事件是否符合已归一化查询条件。</zh-CN>
        ///   <en>Determines whether a diagnostics entry matches normalized query criteria.</en>
        /// </lang>
        /// </summary>
        /// <param name="entry">
        /// <l>
        ///   <zh-CN>待匹配的结构化诊断事件。</zh-CN>
        ///   <en>The structured diagnostics entry to match.</en>
        /// </l>
        /// </param>
        /// <param name="query">
        /// <l>
        ///   <zh-CN>已归一化的查询条件。</zh-CN>
        ///   <en>The normalized query criteria.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>事件满足日期、级别、分类和事件编号过滤条件时为 <c>true</c>。</zh-CN>
        ///   <en><c>true</c> when the entry satisfies date, level, category, and event-id filters.</en>
        /// </l>
        /// </returns>
        private static bool Matches(PortalDiagnosticEntry entry, PortalDiagnosticQuery query)
        {
            if (entry.UtcTime < query.StartUtc || entry.UtcTime >= query.EndUtcExclusive)
            {
                return false;
            }

            if (!string.IsNullOrEmpty(query.Level) && !string.Equals(entry.Level, query.Level, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            if (!string.IsNullOrEmpty(query.Category) && !string.Equals(entry.Category, query.Category, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            return string.IsNullOrEmpty(query.EventId) ||
                   string.Equals(entry.EventId, query.EventId, StringComparison.Ordinal);
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>从诊断事件编号中读取 UTC 日期。</zh-CN>
        ///   <en>Reads the UTC date embedded in a diagnostics event id.</en>
        /// </lang>
        /// </summary>
        /// <param name="eventId">
        /// <l>
        ///   <zh-CN>待解析的事件编号。</zh-CN>
        ///   <en>The event id to parse.</en>
        /// </l>
        /// </param>
        /// <param name="eventDate">
        /// <l>
        ///   <zh-CN>解析成功后的事件 UTC 日期。</zh-CN>
        ///   <en>The event UTC date when parsing succeeds.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>编号格式和日期均有效时为 <c>true</c>。</zh-CN>
        ///   <en><c>true</c> when both id format and date value are valid.</en>
        /// </l>
        /// </returns>
        private static bool TryGetEventDate(string eventId, out DateTime eventDate)
        {
            eventDate = DateTime.MinValue;
            Match match = EventIdPattern.Match(eventId ?? string.Empty);
            if (!match.Success)
            {
                return false;
            }

            return DateTime.TryParseExact(
                match.Groups["date"].Value,
                "yyyyMMdd",
                CultureInfo.InvariantCulture,
                DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                out eventDate);
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>从受控日志文件名中读取日期和序号。</zh-CN>
        ///   <en>Reads date and sequence from a controlled log file name.</en>
        /// </lang>
        /// </summary>
        /// <param name="fileName">
        /// <l>
        ///   <zh-CN>候选日志文件名。</zh-CN>
        ///   <en>The candidate log file name.</en>
        /// </l>
        /// </param>
        /// <param name="fileDate">
        /// <l>
        ///   <zh-CN>文件名中的 UTC 日期。</zh-CN>
        ///   <en>The UTC date embedded in the file name.</en>
        /// </l>
        /// </param>
        /// <param name="sequence">
        /// <l>
        ///   <zh-CN>文件名中的三位滚动序号。</zh-CN>
        ///   <en>The three-digit rolling sequence embedded in the file name.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>文件名格式、日期和序号均有效时为 <c>true</c>。</zh-CN>
        ///   <en><c>true</c> when file-name format, date, and sequence are all valid.</en>
        /// </l>
        /// </returns>
        private static bool TryGetFileParts(string fileName, out DateTime fileDate, out int sequence)
        {
            fileDate = DateTime.MinValue;
            sequence = 0;
            Match match = FileNamePattern.Match(fileName ?? string.Empty);
            if (!match.Success ||
                !DateTime.TryParseExact(
                    match.Groups["date"].Value,
                    "yyyyMMdd",
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                    out fileDate))
            {
                return false;
            }

            return int.TryParse(match.Groups["sequence"].Value, NumberStyles.None, CultureInfo.InvariantCulture, out sequence);
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>清理并截断文本过滤条件。</zh-CN>
        ///   <en>Trims and truncates a text filter.</en>
        /// </lang>
        /// </summary>
        /// <param name="value">
        /// <l>
        ///   <zh-CN>原始过滤值。</zh-CN>
        ///   <en>The raw filter value.</en>
        /// </l>
        /// </param>
        /// <param name="maximumLength">
        /// <l>
        ///   <zh-CN>允许保留的最大字符数。</zh-CN>
        ///   <en>The maximum number of characters to retain.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>空值返回空字符串；非空值返回裁剪后的文本。</zh-CN>
        ///   <en>An empty string for empty input, otherwise the clamped text.</en>
        /// </l>
        /// </returns>
        private static string NormalizeFilter(string value, int maximumLength)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return string.Empty;
            }

            string normalized = value.Trim();
            return normalized.Substring(0, Math.Min(normalized.Length, maximumLength));
        }
    }
}
