//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class ModuleProbe
    {
        /// <summary>
        /// 已解析模块包状态。
        /// Resolved module-package status.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label PackageLabel;

        /// <summary>
        /// 当前模块实例信息。
        /// Current module-instance information.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ModuleLabel;

        /// <summary>
        /// 当前 Tab 与窗格信息。
        /// Current Tab and pane information.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label PlacementLabel;

        /// <summary>
        /// 当前主题 CSS scope。
        /// Current theme CSS scope.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ThemeScopeLabel;
    }
}
