//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class ModuleProbe
    {
        /// <summary><lang><zh-CN>显示已解析模块包的受控状态信息。</zh-CN><en>Displays controlled status information for the resolved module package.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label PackageLabel;

        /// <summary><lang><zh-CN>显示当前模块实例的受控诊断信息。</zh-CN><en>Displays controlled diagnostic information for the current module instance.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ModuleLabel;

        /// <summary><lang><zh-CN>显示当前 Tab 与窗格放置关系的诊断信息。</zh-CN><en>Displays diagnostic information about the current Tab and pane placement.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label PlacementLabel;

        /// <summary><lang><zh-CN>显示当前主题 CSS scope 的诊断信息。</zh-CN><en>Displays diagnostic information about the current theme CSS scope.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label ThemeScopeLabel;

        /// <summary><lang><zh-CN>显示模块渲染 UTC 标记，仅用于缓存验收。</zh-CN><en>Displays the module-render UTC marker used only for cache verification.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label RenderedUtcLabel;
    }
}
