//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由工具生成。
//     This file was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class BusinessApplicationRequest
    {
        /// <summary>模块状态提示。Module status message.</summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>申请表单面板。Application form panel.</summary>
        protected global::System.Web.UI.WebControls.Panel RequestPanel;

        /// <summary>标题输入框。Title input.</summary>
        protected global::System.Web.UI.WebControls.TextBox TitleTextBox;

        /// <summary>分类下拉框。Category dropdown.</summary>
        protected global::System.Web.UI.WebControls.DropDownList CategoryList;

        /// <summary>摘要输入框。Summary input.</summary>
        protected global::System.Web.UI.WebControls.TextBox SummaryTextBox;

        /// <summary>正文输入框。Body input.</summary>
        protected global::System.Web.UI.WebControls.TextBox BodyTextBox;

        /// <summary>提交按钮。Submit button.</summary>
        protected global::System.Web.UI.WebControls.Button SubmitButton;

        /// <summary>最近申请列表。Recent application list.</summary>
        protected global::System.Web.UI.WebControls.Repeater RecentApplicationsRepeater;
    }
}
