//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class BusinessApplicationRequest
    {
        /// <summary><lang><zh-CN>显示业务申请模块状态提示。</zh-CN><en>Displays the business-application module status message.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary><lang><zh-CN>承载业务申请输入表单的面板。</zh-CN><en>Panel that contains the business-application input form.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel RequestPanel;

        /// <summary><lang><zh-CN>接收业务申请标题的输入框。</zh-CN><en>Input for the business-application title.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox TitleTextBox;

        /// <summary><lang><zh-CN>选择业务申请分类的下拉框。</zh-CN><en>Drop-down that selects the business-application category.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList CategoryList;

        /// <summary><lang><zh-CN>接收业务申请摘要的输入框。</zh-CN><en>Input for the business-application summary.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox SummaryTextBox;

        /// <summary><lang><zh-CN>接收业务申请正文的输入框。</zh-CN><en>Input for the business-application body.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox BodyTextBox;

        /// <summary><lang><zh-CN>提交业务申请的按钮。</zh-CN><en>Button that submits the business application.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Button SubmitButton;

        /// <summary><lang><zh-CN>绑定当前用户近期业务申请的 Repeater。</zh-CN><en>Repeater bound to the current user's recent business applications.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater RecentApplicationsRepeater;
    }
}
