using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ASPNET.StarterKit.Portal
{
    /// <summary>
    /// <lang>
    ///   <zh-CN>协同事项有限状态机的一条合法迁移：当前状态、触发动作与目标状态。</zh-CN>
    ///   <en>One legal transition of the collaboration-item finite-state machine: current status, triggering action, and target status.</en>
    /// </lang>
    /// </summary>
    /// <remarks>
    /// <lang>
    ///   <zh-CN>本结构是不可变值类型，只承载事实；判定逻辑集中在 <see cref="PortalCollaborationItemTransitions"/>。</zh-CN>
    ///   <en>This is an immutable value type that carries only facts; the decision logic lives in <see cref="PortalCollaborationItemTransitions"/>.</en>
    /// </lang>
    /// </remarks>
    public readonly struct CollaborationItemTransition
    {
        /// <summary>
        /// <lang>
        ///   <zh-CN>用当前状态、触发动作与目标状态构造一条迁移。</zh-CN>
        ///   <en>Constructs a transition from the current status, triggering action, and target status.</en>
        /// </lang>
        /// </summary>
        /// <param name="fromStatus">
        /// <l>
        ///   <zh-CN>迁移前的当前状态，应来自 <see cref="PortalCollaborationItemStatuses"/>。</zh-CN>
        ///   <en>Status before the transition, expected to come from <see cref="PortalCollaborationItemStatuses"/>.</en>
        /// </l>
        /// </param>
        /// <param name="actionKey">
        /// <l>
        ///   <zh-CN>触发动作键，应来自 <see cref="PortalCollaborationItemActions"/>。</zh-CN>
        ///   <en>Triggering action key, expected to come from <see cref="PortalCollaborationItemActions"/>.</en>
        /// </l>
        /// </param>
        /// <param name="toStatus">
        /// <l>
        ///   <zh-CN>迁移后的目标状态，应来自 <see cref="PortalCollaborationItemStatuses"/>。</zh-CN>
        ///   <en>Status after the transition, expected to come from <see cref="PortalCollaborationItemStatuses"/>.</en>
        /// </l>
        /// </param>
        public CollaborationItemTransition(string fromStatus, string actionKey, string toStatus)
        {
            FromStatus = fromStatus;
            ActionKey = actionKey;
            ToStatus = toStatus;
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>迁移前的当前状态。</zh-CN>
        ///   <en>Status before the transition.</en>
        /// </lang>
        /// </summary>
        public string FromStatus { get; }

        /// <summary>
        /// <lang>
        ///   <zh-CN>触发动作键。</zh-CN>
        ///   <en>Triggering action key.</en>
        /// </lang>
        /// </summary>
        public string ActionKey { get; }

        /// <summary>
        /// <lang>
        ///   <zh-CN>迁移后的目标状态。</zh-CN>
        ///   <en>Status after the transition.</en>
        /// </lang>
        /// </summary>
        public string ToStatus { get; }
    }

    /// <summary>
    /// <lang>
    ///   <zh-CN>协同事项有限状态机的显式合法迁移表，作为状态/动作/目标状态的单一事实源。</zh-CN>
    ///   <en>Explicit legal-transition table of the collaboration-item finite-state machine, serving as the single source of truth for status, action, and target status.</en>
    /// </lang>
    /// </summary>
    /// <remarks>
    /// <lang>
    ///   <zh-CN>本类是 P64 状态机显式化的核心：把原先散落在 SQL 字符串与 <c>MapActionToStatus</c> if-链中的两份事实收敛成一份可单测的数据。动作到目标状态在当前设计中唯一（即同一动作不论从哪个当前状态出发，目标相同），因此 <see cref="TryGetTargetStatus"/> 与 <c>MapActionToStatus</c> 可由本表派生；数据库写入守卫的 SQL 谓词也由 <see cref="BuildSqlStatusPredicate"/> 生成，避免与表漂移。本类不读取数据库、不依赖 HTTP 上下文，可在单测中直接验证。</zh-CN>
    ///   <en>This class is the core of the P64 state-machine explicitization: it collapses the two earlier fact copies—the SQL string and the <c>MapActionToStatus</c> if-chain—into one testable dataset. The action-to-target mapping is unique in the current design (an action always reaches the same target regardless of the source status), so <see cref="TryGetTargetStatus"/> and <c>MapActionToStatus</c> derive from this table; the SQL predicate used as the database write guard is also generated by <see cref="BuildSqlStatusPredicate"/> to avoid drift. The class reads no database and depends on no HTTP context, so it can be verified directly in unit tests.</en>
    /// </lang>
    /// </remarks>
    public static class PortalCollaborationItemTransitions
    {
        /// <summary>
        /// <lang>
        ///   <zh-CN>全部合法迁移，逐条对应既有 SQL 守卫中编码的 15 条迁移；新增或移除状态机迁移只需改此集合。</zh-CN>
        ///   <en>All legal transitions, each corresponding to one of the 15 transitions previously encoded in the SQL guard; add or remove a machine transition only by editing this collection.</en>
        /// </lang>
        /// </summary>
        public static readonly IReadOnlyList<CollaborationItemTransition> All = new[]
        {
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Draft, PortalCollaborationItemActions.Submit, PortalCollaborationItemStatuses.Submitted),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Submitted, PortalCollaborationItemActions.Start, PortalCollaborationItemStatuses.InProgress),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Submitted, PortalCollaborationItemActions.Complete, PortalCollaborationItemStatuses.Completed),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.InProgress, PortalCollaborationItemActions.Complete, PortalCollaborationItemStatuses.Completed),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Submitted, PortalCollaborationItemActions.Return, PortalCollaborationItemStatuses.Returned),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.InProgress, PortalCollaborationItemActions.Return, PortalCollaborationItemStatuses.Returned),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Returned, PortalCollaborationItemActions.Resubmit, PortalCollaborationItemStatuses.Submitted),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Submitted, PortalCollaborationItemActions.Reject, PortalCollaborationItemStatuses.Rejected),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.InProgress, PortalCollaborationItemActions.Reject, PortalCollaborationItemStatuses.Rejected),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Draft, PortalCollaborationItemActions.Cancel, PortalCollaborationItemStatuses.Cancelled),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Submitted, PortalCollaborationItemActions.Cancel, PortalCollaborationItemStatuses.Cancelled),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Returned, PortalCollaborationItemActions.Cancel, PortalCollaborationItemStatuses.Cancelled),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Completed, PortalCollaborationItemActions.Close, PortalCollaborationItemStatuses.Closed),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Rejected, PortalCollaborationItemActions.Close, PortalCollaborationItemStatuses.Closed),
            new CollaborationItemTransition(PortalCollaborationItemStatuses.Cancelled, PortalCollaborationItemActions.Close, PortalCollaborationItemStatuses.Closed)
        };

        // <lang>
        //   <zh-CN>动作固定顺序，使生成的 SQL 谓词与既有手写谓词逐动作对齐，便于等价断言。</zh-CN>
        //   <en>Fixed action order so the generated SQL predicate aligns action-by-action with the established hand-written predicate, aiding equivalence assertions.</en>
        // </lang>
        private static readonly string[] ActionOrder =
        {
            PortalCollaborationItemActions.Submit,
            PortalCollaborationItemActions.Start,
            PortalCollaborationItemActions.Complete,
            PortalCollaborationItemActions.Return,
            PortalCollaborationItemActions.Resubmit,
            PortalCollaborationItemActions.Reject,
            PortalCollaborationItemActions.Cancel,
            PortalCollaborationItemActions.Close
        };

        /// <summary>
        /// <lang>
        ///   <zh-CN>按当前状态与动作解析目标状态；存在合法迁移即返回其目标状态。</zh-CN>
        ///   <en>Resolves the target status from the current status and action; returns the target status when a legal transition exists.</en>
        /// </lang>
        /// </summary>
        /// <param name="fromStatus">
        /// <l>
        ///   <zh-CN>迁移前的当前状态。</zh-CN>
        ///   <en>Status before the transition.</en>
        /// </l>
        /// </param>
        /// <param name="actionKey">
        /// <l>
        ///   <zh-CN>触发动作键。</zh-CN>
        ///   <en>Triggering action key.</en>
        /// </l>
        /// </param>
        /// <param name="toStatus">
        /// <l>
        ///   <zh-CN>输出参数：合法迁移的目标状态；不存在时输出空引用。</zh-CN>
        ///   <en>Output: the target status of a legal transition; null when none exists.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>存在合法迁移时为 <c>true</c>；动作未知或当前状态不允许该动作时为 <c>false</c>（fail-closed）。</zh-CN>
        ///   <en><c>true</c> when a legal transition exists; <c>false</c> when the action is unknown or the current status does not allow it (fail-closed).</en>
        /// </l>
        /// </returns>
        public static bool TryGetTargetStatus(string fromStatus, string actionKey, out string toStatus)
        {
            CollaborationItemTransition transition = All.FirstOrDefault(candidate =>
                string.Equals(candidate.FromStatus, fromStatus, StringComparison.Ordinal) &&
                string.Equals(candidate.ActionKey, actionKey, StringComparison.Ordinal));

            if (transition.ToStatus == null)
            {
                toStatus = null;
                return false;
            }

            toStatus = transition.ToStatus;
            return true;
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>判定从给定当前状态发起给定动作是否为合法迁移（fail-closed）。</zh-CN>
        ///   <en>Decides whether starting a given action from the given current status is a legal transition (fail-closed).</en>
        /// </lang>
        /// </summary>
        /// <param name="fromStatus">
        /// <l>
        ///   <zh-CN>迁移前的当前状态。</zh-CN>
        ///   <en>Status before the transition.</en>
        /// </l>
        /// </param>
        /// <param name="actionKey">
        /// <l>
        ///   <zh-CN>触发动作键。</zh-CN>
        ///   <en>Triggering action key.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>存在 <c>(from, action)</c> 迁移行为 <c>true</c>；空或未知状态/动作为 <c>false</c>。</zh-CN>
        ///   <en><c>true</c> when an <c>(from, action)</c> transition exists; <c>false</c> for empty or unknown status/action.</en>
        /// </l>
        /// </returns>
        public static bool IsLegalTransition(string fromStatus, string actionKey)
        {
            if (string.IsNullOrEmpty(fromStatus) || string.IsNullOrEmpty(actionKey))
            {
                return false;
            }

            return All.Any(candidate =>
                string.Equals(candidate.FromStatus, fromStatus, StringComparison.Ordinal) &&
                string.Equals(candidate.ActionKey, actionKey, StringComparison.Ordinal));
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>返回某动作允许出现的当前状态集合（去重）。</zh-CN>
        ///   <en>Returns the distinct current statuses from which an action is allowed.</en>
        /// </lang>
        /// </summary>
        /// <param name="actionKey">
        /// <l>
        ///   <zh-CN>触发动作键。</zh-CN>
        ///   <en>Triggering action key.</en>
        /// </l>
        /// </param>
        /// <returns>
        /// <l>
        ///   <zh-CN>允许出现的当前状态列表；动作未知时为空集合。</zh-CN>
        ///   <en>The allowed current statuses; an empty collection when the action is unknown.</en>
        /// </l>
        /// </returns>
        public static IReadOnlyList<string> AllowedFromStatuses(string actionKey)
        {
            return All
                .Where(candidate => string.Equals(candidate.ActionKey, actionKey, StringComparison.Ordinal))
                .Select(candidate => candidate.FromStatus)
                .Distinct()
                .ToList();
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>由 <see cref="All"/> 生成与既有手写谓词等价的 SQL <c>WHERE</c> 子句，使数据库写入守卫与迁移表同源。</zh-CN>
        ///   <en>Generates the SQL <c>WHERE</c> clause equivalent to the established hand-written predicate from <see cref="All"/>, so the database write guard shares one source with the transition table.</en>
        /// </lang>
        /// </summary>
        /// <returns>
        /// <l>
        ///   <zh-CN>形如 `(@ActionKey = N'X' AND [ItemStatus] = N'Y') OR ...` 的谓词片段，不含外层括号。</zh-CN>
        ///   <en>A predicate fragment like `(@ActionKey = N'X' AND [ItemStatus] = N'Y') OR ...`, without outer parentheses.</en>
        /// </l>
        /// </returns>
        /// <remarks>
        /// <lang>
        ///   <zh-CN>动作键与状态值均来自受控常量（非用户输入），字符串拼接安全；单值用 `=`，多值用 `IN (...)`，保持与原谓词一致的格式以便等价断言。</zh-CN>
        ///   <en>Action keys and status values come only from controlled constants (not user input), so string concatenation is safe; a single value uses `=`, multiple values use `IN (...)`, keeping the same format as the original predicate for equivalence assertions.</en>
        /// </lang>
        /// </remarks>
        public static string BuildSqlStatusPredicate()
        {
            StringBuilder predicate = new StringBuilder();
            bool isFirstAction = true;

            foreach (string action in ActionOrder)
            {
                IReadOnlyList<string> fromStatuses = AllowedFromStatuses(action);
                if (fromStatuses.Count == 0)
                {
                    continue;
                }

                if (!isFirstAction)
                {
                    predicate.Append(" OR ");
                }

                isFirstAction = false;
                predicate.Append("(@ActionKey = N'").Append(action).Append("' AND [ItemStatus]");

                if (fromStatuses.Count == 1)
                {
                    predicate.Append(" = N'").Append(fromStatuses[0]).Append("'");
                }
                else
                {
                    predicate.Append(" IN (");
                    for (int index = 0; index < fromStatuses.Count; index++)
                    {
                        if (index > 0)
                        {
                            predicate.Append(", ");
                        }

                        predicate.Append("N'").Append(fromStatuses[index]).Append("'");
                    }

                    predicate.Append(")");
                }

                predicate.Append(")");
            }

            return predicate.ToString();
        }
    }
}
