<#
.SYNOPSIS
    向 lang.resx、lang.zh-cn.resx 与签入的强类型 lang.designer.cs 同批追加本地化键。

.DESCRIPTION
    # <lang>
    #   <zh-CN>
    #     为什么需要本工具：资源键加进 resx 并不会自动出现在签入的强类型 `lang` 类里
    #     （designer 由 Visual Studio 的自定义工具生成，命令行构建不会重跑它），
    #     因此只改 resx 会在编译期报 CS0117。本工具把三处改动绑定为一次原子操作，
    #     并立即校验两 resx 键数一致、每个新键双侧存在——把该返工从"事后发现"变成"当场拦住"。
    #
    #     输入为 JSON 数组，每项形如 { "key": "Subtitle", "en": "…", "zh": "…" }，
    #     key 为**不含页前缀后缀名**；最终键名 = -Prefix + key。
    #     插入位置为各文件中第一个以该前缀开头的既有条目之前，保证同页键聚在一起、便于审阅。
    #   </zh-CN>
    #   <en>
    #     Why this tool exists: adding a key to the resx files does not automatically add it to the
    #     checked-in strongly typed `lang` class (the designer is generated by a Visual Studio custom tool
    #     and command-line builds do not rerun it), so changing only the resx files fails compilation with
    #     CS0117. This tool binds the three edits into one atomic operation and immediately verifies that the
    #     two resx files have equal key counts and that every new key exists in both, turning that rework from
    #     a late discovery into an immediate guard.
    #
    #     Input is a JSON array of { "key": "Subtitle", "en": "...", "zh": "..." } where key excludes the page
    #     prefix; the final key name is -Prefix + key. Entries are inserted before the first existing entry
    #     starting with that prefix in each file, so page keys stay grouped and easy to review.
    #   </en>
    # </lang>

.PARAMETER Prefix
    键前缀，例如 Admin_EmployeeEdit_。

.PARAMETER KeysJsonPath
    键定义 JSON 文件路径（UTF-8）。

.EXAMPLE
    pwsh -File dev/scripts/Add-PortalLocalizationKeys.ps1 -Prefix Admin_EmployeeEdit_ -KeysJsonPath temp/keys.json
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Prefix,
    [Parameter(Mandatory)][ValidateScript({ Test-Path -LiteralPath $_ -PathType Leaf })][string]$KeysJsonPath,

    # <lang>
    #   <zh-CN>可选：当该页此前没有任何键（故无从按前缀定位）时，指定一个既有键名作为插入锚点。</zh-CN>
    #   <en>Optional: when the page has no keys yet (so no prefix anchor exists), name an existing key to insert before.</en>
    # </lang>
    [string]$AnchorName
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$base = Join-Path (Join-Path $PSScriptRoot '..\..') 'src\Portal\App_GlobalResources'
$enPath = Join-Path $base 'lang.resx'
$zhPath = Join-Path $base 'lang.zh-cn.resx'
$designerPath = Join-Path $base 'lang.designer.cs'

$defs = [IO.File]::ReadAllText((Resolve-Path $KeysJsonPath).Path) | ConvertFrom-Json
if (-not $defs -or $defs.Count -eq 0) { throw '键定义为空' }

# <lang>
#   <zh-CN>先拒绝重复插入：若键已存在则整体失败，避免把同一批键加两遍。</zh-CN>
#   <en>Reject duplicate insertion up front: fail the whole run if a key already exists, so a batch cannot be applied twice.</en>
# </lang>
foreach ($d in $defs) {
    if ([string]::IsNullOrWhiteSpace($d.key)) { throw '存在空的 key' }
    $full = $Prefix + $d.key
    $exists = Select-String -LiteralPath $enPath -SimpleMatch ('name="' + $full + '"')
    if ($exists) { throw "键已存在，拒绝重复插入: $full" }
}

function Insert-ResxEntries {
    param([string]$Path, [ValidateSet('en', 'zh')][string]$Lang)

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.AddRange([IO.File]::ReadAllLines($Path))
    $needle = if ($AnchorName) { 'name="' + $AnchorName + '"' } else { 'name="' + $Prefix }
    $at = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -like ('*' + $needle + '*')) { $at = $i; break }
    }
    if ($at -lt 0) { throw "未找到插入锚点（$needle）: $Path" }

    $block = New-Object System.Collections.Generic.List[string]
    foreach ($d in $defs) {
        $block.Add(('  <data name="{0}{1}" xml:space="preserve">' -f $Prefix, $d.key))
        $block.Add(('    <value>{0}</value>' -f $d.$Lang))
        $block.Add('  </data>')
    }
    $lines.InsertRange($at, $block)
    [IO.File]::WriteAllLines($Path, $lines, (New-Object System.Text.UTF8Encoding $false))
    Write-Host ("  {0} : 插入 {1} 条（锚点行 {2}）" -f [IO.Path]::GetFileName($Path), $defs.Count, $at)
}

function Insert-DesignerProperties {
    param([string]$Path)

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.AddRange([IO.File]::ReadAllLines($Path))
    $needle = 'internal static string ' + $(if ($AnchorName) { $AnchorName + ' ' } else { $Prefix })
    $at = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -like ('*' + $needle + '*')) { $at = $i; break }
    }
    if ($at -lt 0) { throw "未找到 designer 插入锚点（$needle）: $Path" }

    $indent = $lines[$at].Substring(0, $lines[$at].Length - $lines[$at].TrimStart().Length)
    $block = New-Object System.Collections.Generic.List[string]
    foreach ($d in $defs) {
        $name = $Prefix + $d.key
        $block.Add($indent + '/// <summary>')
        $block.Add($indent + '/// <lang>')
        $block.Add($indent + '///   <zh-CN>查找类似以下内容的本地化字符串：' + $d.en + '</zh-CN>')
        $block.Add($indent + '///   <en>Looks up a localized string similar to: ' + $d.en + '</en>')
        $block.Add($indent + '/// </lang>')
        $block.Add($indent + '/// </summary>')
        $block.Add($indent + 'internal static string ' + $name + ' {')
        $block.Add($indent + '    get {')
        $block.Add($indent + '        return ResourceManager.GetString("' + $name + '", resourceCulture);')
        $block.Add($indent + '    }')
        $block.Add($indent + '}')
        $block.Add('')
    }
    $lines.InsertRange($at, $block)
    [IO.File]::WriteAllLines($Path, $lines, (New-Object System.Text.UTF8Encoding $false))
    Write-Host ("  lang.designer.cs : 插入 {0} 个属性（锚点行 {1}）" -f $defs.Count, $at)
}

Insert-ResxEntries -Path $enPath -Lang 'en'
Insert-ResxEntries -Path $zhPath -Lang 'zh'
Insert-DesignerProperties -Path $designerPath

$en = [xml][IO.File]::ReadAllText($enPath)
$zh = [xml][IO.File]::ReadAllText($zhPath)
$enN = ($en.root.data | Where-Object { $_.name }).Count
$zhN = ($zh.root.data | Where-Object { $_.name }).Count
$bad = 0
foreach ($d in $defs) {
    $full = $Prefix + $d.key
    if (($en.root.data | Where-Object { $_.name -eq $full }).Count -ne 1) { $bad++; Write-Host "  en 侧异常: $full" }
    if (($zh.root.data | Where-Object { $_.name -eq $full }).Count -ne 1) { $bad++; Write-Host "  zh 侧异常: $full" }
}
$ok = ($enN -eq $zhN) -and ($bad -eq 0)
Write-Host ("  校验: en={0} zh={1} 键数一致={2} 异常键={3} -> {4}" -f $enN, $zhN, ($enN -eq $zhN), $bad, $(if ($ok) { 'PASS' } else { 'FAIL' }))
if (-not $ok) { exit 1 }
