<#
.SYNOPSIS
<lang>
  <en>Generates a development/test mount SQL for any portal module package.</en>
  <zh-CN>为任意门户模块包生成开发/测试挂载 SQL。</zh-CN>
</lang>

.DESCRIPTION
<lang>
  <en>Emits a reviewable, idempotent SQL file that registers a module definition, enables the package state, and creates or updates a test Tab plus one module instance. It generalizes the P22.4 per-module seed so later modules (for example MyWorkItems) do not need their own script. The script writes a file only; it never connects to SQL Server, so execution stays a separate, visible step.</en>
  <zh-CN>生成一份可审阅、幂等的 SQL：注册模块定义、启用包状态，并创建或更新测试 Tab 与一个模块实例。它把 P22.4 的"每模块一份 seed"泛化，使后续模块（例如 MyWorkItems）不必再各写脚本。脚本只写文件，不连接 SQL Server，因此"执行"仍是独立且可见的一步。</zh-CN>
</lang>

.PARAMETER OutputPath
<lang>
  <en>Target SQL file path.</en>
  <zh-CN>目标 SQL 文件路径。</zh-CN>
</lang>

.PARAMETER TabName
<lang>
  <en>Test Tab name to create or update.</en>
  <zh-CN>要创建或更新的测试 Tab 名称。</zh-CN>
</lang>

.PARAMETER ModuleTitle
<lang>
  <en>Module instance title shown in the module header.</en>
  <zh-CN>模块实例标题，显示在模块标题栏。</zh-CN>
</lang>

.PARAMETER FriendlyName
<lang>
  <en>Module definition friendly name.</en>
  <zh-CN>模块定义友好名称。</zh-CN>
</lang>

.PARAMETER DesktopSource
<lang>
  <en>Module desktop source file path, relative to the site root.</en>
  <zh-CN>模块桌面源文件路径（相对站点根）。</zh-CN>
</lang>

.PARAMETER PackageId
<lang>
  <en>Module package identifier enabled in the package-state table.</en>
  <zh-CN>在包状态表中启用的模块包标识。</zh-CN>
</lang>

.PARAMETER Actor
<lang>
  <en>Actor recorded in the package-state audit columns.</en>
  <zh-CN>写入包状态审计列的操作用户。</zh-CN>
</lang>
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$OutputPath,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$TabName,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$ModuleTitle,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$FriendlyName,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$DesktopSource,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$PackageId,

    [ValidateNotNullOrEmpty()]
    [string]$Actor = 'ModuleScenarioSeed',

    [ValidateRange(1, 2147483647)]
    [int]$PortalId = 1,

    [ValidateNotNullOrEmpty()]
    [string]$AccessRoles = 'All Users;',

    [ValidateNotNullOrEmpty()]
    [string]$EditRoles = 'Admins;'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# <lang>
#   <zh-CN>把输入转换为单引号包围的 Unicode 字面量，单引号加倍转义；空值保持 NULL。只生成文本，不做任何连接。</zh-CN>
#   <en>Converts an input to a single-quoted Unicode literal with doubled apostrophes; blank input stays NULL. This only produces text and never connects anywhere.</en>
# </lang>
function ConvertTo-SqlLiteral {
    param([AllowNull()][string]$Value)

    if ([string]::IsNullOrEmpty($Value)) {
        return 'NULL'
    }

    return "N'" + ($Value -replace "'", "''") + "'"
}

$sql = @"
/*

    Module scenario mount script (generated by dev/scripts/New-PortalModuleScenarioSql.ps1).

    模块场景挂载脚本（由 dev/scripts/New-PortalModuleScenarioSql.ps1 生成）。

    Boundary: development/test databases only; this registers a Tab, module definition,
    module instance, and package enablement, and does not create users or write credentials.

    边界：仅用于开发/测试库；只注册 Tab、模块定义、模块实例与包启用状态，不创建用户、不写凭据。

*/
SET XACT_ABORT ON;
SET NOCOUNT ON;

DECLARE @PortalId INT = $PortalId;
DECLARE @TabName NVARCHAR(150) = $(ConvertTo-SqlLiteral $TabName);
DECLARE @ModuleTitle NVARCHAR(150) = $(ConvertTo-SqlLiteral $ModuleTitle);
DECLARE @AccessRoles NVARCHAR(250) = $(ConvertTo-SqlLiteral $AccessRoles);
DECLARE @EditRoles NVARCHAR(250) = $(ConvertTo-SqlLiteral $EditRoles);
DECLARE @FriendlyName NVARCHAR(150) = $(ConvertTo-SqlLiteral $FriendlyName);
DECLARE @DesktopSource NVARCHAR(250) = $(ConvertTo-SqlLiteral $DesktopSource);
DECLARE @PackageId NVARCHAR(100) = $(ConvertTo-SqlLiteral $PackageId);
DECLARE @Actor NVARCHAR(100) = $(ConvertTo-SqlLiteral $Actor);

IF OBJECT_ID(N'[dbo].[PortalCfg_ModuleDefinitions]', N'U') IS NULL
    OR OBJECT_ID(N'[dbo].[PortalCfg_Tabs]', N'U') IS NULL
    OR OBJECT_ID(N'[dbo].[PortalCfg_Modules]', N'U') IS NULL
    OR OBJECT_ID(N'[dbo].[PortalCfg_ModulePackageStates]', N'U') IS NULL
BEGIN
    RAISERROR(N'Module scenario requires the P3 module configuration schema.', 16, 1);
    RETURN;
END

BEGIN TRANSACTION;

DECLARE @ModuleDefId INT;
SELECT TOP (1) @ModuleDefId = [ModuleDefId]
FROM [dbo].[PortalCfg_ModuleDefinitions]
WHERE [DesktopSourceFile] = @DesktopSource
ORDER BY [ModuleDefId];

IF @ModuleDefId IS NULL
BEGIN
    INSERT INTO [dbo].[PortalCfg_ModuleDefinitions] ([FriendlyName], [DesktopSourceFile], [MobileSourceFile])
    VALUES (@FriendlyName, @DesktopSource, N'');
    SET @ModuleDefId = CONVERT(INT, SCOPE_IDENTITY());
END
ELSE
BEGIN
    UPDATE [dbo].[PortalCfg_ModuleDefinitions]
    SET [FriendlyName] = @FriendlyName,
        [MobileSourceFile] = N''
    WHERE [ModuleDefId] = @ModuleDefId;
END

IF EXISTS (SELECT 1 FROM [dbo].[PortalCfg_ModulePackageStates] WHERE [PackageId] = @PackageId)
BEGIN
    UPDATE [dbo].[PortalCfg_ModulePackageStates]
    SET [IsEnabled] = 1,
        [Note] = N'Enabled by module scenario seed.',
        [UpdatedBy] = @Actor,
        [UpdatedUtc] = SYSUTCDATETIME()
    WHERE [PackageId] = @PackageId;
END
ELSE
BEGIN
    INSERT INTO [dbo].[PortalCfg_ModulePackageStates] ([PackageId], [IsEnabled], [Note], [UpdatedBy], [UpdatedUtc])
    VALUES (@PackageId, 1, N'Enabled by module scenario seed.', @Actor, SYSUTCDATETIME());
END

DECLARE @TabId INT;
SELECT TOP (1) @TabId = [TabId]
FROM [dbo].[PortalCfg_Tabs]
WHERE [PortalId] = @PortalId AND [TabName] = @TabName
ORDER BY [TabId];

IF @TabId IS NULL
BEGIN
    DECLARE @TabOrder INT;
    SELECT @TabOrder = ISNULL(MAX([TabOrder]), 0) + 2
    FROM [dbo].[PortalCfg_Tabs]
    WHERE [PortalId] = @PortalId;

    INSERT INTO [dbo].[PortalCfg_Tabs]
        ([TabName], [TabOrder], [AccessRoles], [ShowMobile], [MobileTabName], [PortalId])
    VALUES
        (@TabName, @TabOrder, @AccessRoles, 0, @TabName, @PortalId);
    SET @TabId = CONVERT(INT, SCOPE_IDENTITY());
END
ELSE
BEGIN
    UPDATE [dbo].[PortalCfg_Tabs]
    SET [AccessRoles] = @AccessRoles,
        [ShowMobile] = 0,
        [MobileTabName] = @TabName
    WHERE [TabId] = @TabId;
END

DECLARE @ModuleId INT;
SELECT TOP (1) @ModuleId = [ModuleId]
FROM [dbo].[PortalCfg_Modules]
WHERE [TabId] = @TabId AND [ModuleDefId] = @ModuleDefId
ORDER BY [ModuleId];

IF @ModuleId IS NULL
BEGIN
    DECLARE @ModuleOrder INT;
    SELECT @ModuleOrder = ISNULL(MAX([ModuleOrder]), 0) + 1
    FROM [dbo].[PortalCfg_Modules]
    WHERE [TabId] = @TabId AND [PaneName] = N'ContentPane';

    INSERT INTO [dbo].[PortalCfg_Modules]
        ([ModuleTitle], [ModuleOrder], [EditRoles], [PaneName], [ShowMobile], [CacheTimeout], [ModuleDefId], [TabId])
    VALUES
        (@ModuleTitle, @ModuleOrder, @EditRoles, N'ContentPane', 0, 0, @ModuleDefId, @TabId);
    SET @ModuleId = CONVERT(INT, SCOPE_IDENTITY());
END
ELSE
BEGIN
    UPDATE [dbo].[PortalCfg_Modules]
    SET [ModuleTitle] = @ModuleTitle,
        [EditRoles] = @EditRoles,
        [PaneName] = N'ContentPane',
        [ShowMobile] = 0,
        [CacheTimeout] = 0
    WHERE [ModuleId] = @ModuleId;
END

COMMIT TRANSACTION;

SELECT
    @TabId AS [ScenarioTabId],
    @ModuleDefId AS [ScenarioModuleDefId],
    @ModuleId AS [ScenarioModuleId],
    @PackageId AS [ScenarioPackageId],
    @TabName AS [ScenarioTabName];
"@

$targetPath = [System.IO.Path]::GetFullPath($OutputPath)
$directory = [System.IO.Path]::GetDirectoryName($targetPath)
if (-not [string]::IsNullOrEmpty($directory)) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

[System.IO.File]::WriteAllText($targetPath, $sql, [System.Text.UTF8Encoding]::new($false))
Write-Host "Module scenario SQL written: $targetPath"
