//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;


    /// <summary>
    /// <lang>
    ///   <zh-CN>强类型资源访问器，用于查找本地化字符串等资源值。</zh-CN>
    ///   <en>Strongly typed resource accessor used to look up localized strings and related resource values.</en>
    /// </lang>
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>返回此强类型资源访问器使用的缓存 ResourceManager 实例。</zh-CN>
        ///   <en>Returns the cached ResourceManager instance used by this strongly typed resource accessor.</en>
        /// </lang>
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>重写当前线程的 CurrentUICulture，影响此强类型资源类执行的所有资源查找。</zh-CN>
        ///   <en>Overrides the current thread CurrentUICulture for all lookups performed by this strongly typed resource class.</en>
        /// </lang>
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Access Denied</zh-CN>
        ///   <en>Looks up a localized string similar to: Access Denied</en>
        /// </lang>
        /// </summary>
        internal static string Admin_AccessDenied_AccessDenied {
            get {
                return ResourceManager.GetString("Admin_AccessDenied_AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Either you are not currently logged in, or you do not have access to this tab page within the portal. Please contact the portal administrator to obtain access.</zh-CN>
        ///   <en>Looks up a localized string similar to: Either you are not currently logged in, or you do not have access to this tab page within the portal. Please contact the portal administrator to obtain access.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_AccessDenied_DeniedAbout {
            get {
                return ResourceManager.GetString("Admin_AccessDenied_DeniedAbout", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Return to the ASP.NET Portal Starter Kit Home</zh-CN>
        ///   <en>Looks up a localized string similar to: Return to the ASP.NET Portal Starter Kit Home</en>
        /// </lang>
        /// </summary>
        internal static string Admin_AccessDenied_ReturnToHome {
            get {
                return ResourceManager.GetString("Admin_AccessDenied_ReturnToHome", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Edit Access Denied</zh-CN>
        ///   <en>Looks up a localized string similar to: Edit Access Denied</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EditAccessDenied_EditAccessDenied {
            get {
                return ResourceManager.GetString("Admin_EditAccessDenied_EditAccessDenied", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Add user to this role</zh-CN>
        ///   <en>Looks up a localized string similar to: Add user to this role</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_AddUserToRole {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_AddUserToRole", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Apply Name and Password Changes</zh-CN>
        ///   <en>Looks up a localized string similar to: Apply Name and Password Changes</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_ApplyNamePwdChange {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_ApplyNamePwdChange", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Confirm Password:</zh-CN>
        ///   <en>Looks up a localized string similar to: Confirm Password:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_ConfirmPwd {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_ConfirmPwd", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Email (or Windows domain name):</zh-CN>
        ///   <en>Looks up a localized string similar to: Email (or Windows domain name):</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_Email {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_Email", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Manage User</zh-CN>
        ///   <en>Looks up a localized string similar to: Manage User</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_ManageUser {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_ManageUser", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Password:</zh-CN>
        ///   <en>Looks up a localized string similar to: Password:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_Password {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_Password", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Remove user from this role</zh-CN>
        ///   <en>Looks up a localized string similar to: Remove user from this role</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_RemoveFromRoleAlt {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_RemoveFromRoleAlt", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Remove</zh-CN>
        ///   <en>Looks up a localized string similar to: Remove</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_RemoveFromRoleText {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_RemoveFromRoleText", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Save User Changes</zh-CN>
        ///   <en>Looks up a localized string similar to: Save User Changes</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_SaveUserChange {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_SaveUserChange", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Users must be registered to view secure content. Users may add themselves using the Register form, and Administrators may add users to specific roles using the Security Roles function above. This section permits Administrators to manage users and their security roles directly.</zh-CN>
        ///   <en>Looks up a localized string similar to: Users must be registered to view secure content. Users may add themselves using the Register form, and Administrators may add users to specific roles using the Security Roles function above. This section permits Administrators to manage users and their security roles directly.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_Users_FormMsg {
            get {
                return ResourceManager.GetString("Admin_Users_FormMsg", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Domain users do not need to be registered to access portal content that is available to \"All Users\". Administrators may add domain users to specific roles using the Security Roles function above. This section permits Administrators to manage users and their security roles directly.</zh-CN>
        ///   <en>Looks up a localized string similar to: Domain users do not need to be registered to access portal content that is available to \"All Users\". Administrators may add domain users to specific roles using the Security Roles function above. This section permits Administrators to manage users and their security roles directly.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_Users_OtherMsg {
            get {
                return ResourceManager.GetString("Admin_Users_OtherMsg", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Registered Users:</zh-CN>
        ///   <en>Looks up a localized string similar to: Registered Users:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_Users_RegisteredUsers {
            get {
                return ResourceManager.GetString("Admin_Users_RegisteredUsers", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Add New User</zh-CN>
        ///   <en>Looks up a localized string similar to: Add New User</en>
        /// </lang>
        /// </summary>
        internal static string Admin_User_AddUser {
            get {
                return ResourceManager.GetString("Admin_User_AddUser", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Delete this user</zh-CN>
        ///   <en>Looks up a localized string similar to: Delete this user</en>
        /// </lang>
        /// </summary>
        internal static string Admin_User_DelUser {
            get {
                return ResourceManager.GetString("Admin_User_DelUser", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Edit this user</zh-CN>
        ///   <en>Looks up a localized string similar to: Edit this user</en>
        /// </lang>
        /// </summary>
        internal static string Admin_User_EditUser {
            get {
                return ResourceManager.GetString("Admin_User_EditUser", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：read more...</zh-CN>
        ///   <en>Looks up a localized string similar to: read more...</en>
        /// </lang>
        /// </summary>
        internal static string Announcements_readMore {
            get {
                return ResourceManager.GetString("Announcements_readMore", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Manage Users</zh-CN>
        ///   <en>Looks up a localized string similar to: Manage Users</en>
        /// </lang>
        /// </summary>
        internal static string Module_Name_ID_32 {
            get {
                return ResourceManager.GetString("Module_Name_ID_32", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Account Login</zh-CN>
        ///   <en>Looks up a localized string similar to: Account Login</en>
        /// </lang>
        /// </summary>
        internal static string Signin_accountLogin {
            get {
                return ResourceManager.GetString("Signin_accountLogin", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Email:</zh-CN>
        ///   <en>Looks up a localized string similar to: Email:</en>
        /// </lang>
        /// </summary>
        internal static string Signin_email {
            get {
                return ResourceManager.GetString("Signin_email", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Email Or Name:</zh-CN>
        ///   <en>Looks up a localized string similar to: Email Or Name:</en>
        /// </lang>
        /// </summary>
        internal static string Signin_EmailOrName {
            get {
                return ResourceManager.GetString("Signin_EmailOrName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Login Failed!</zh-CN>
        ///   <en>Looks up a localized string similar to: Login Failed!</en>
        /// </lang>
        /// </summary>
        internal static string Signin_LoginFaild {
            get {
                return ResourceManager.GetString("Signin_LoginFaild", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Password:</zh-CN>
        ///   <en>Looks up a localized string similar to: Password:</en>
        /// </lang>
        /// </summary>
        internal static string Signin_password {
            get {
                return ResourceManager.GetString("Signin_password", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Remember Login</zh-CN>
        ///   <en>Looks up a localized string similar to: Remember Login</en>
        /// </lang>
        /// </summary>
        internal static string Signin_rememberLogin {
            get {
                return ResourceManager.GetString("Signin_rememberLogin", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：System Health</zh-CN>
        ///   <en>Looks up a localized string similar to: System Health</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_Title {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Runtime diagnostics and configuration registry overview.</zh-CN>
        ///   <en>Looks up a localized string similar to: Runtime diagnostics and configuration registry overview.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_Subtitle {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Overall Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Overall Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_OverallStatus {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_OverallStatus", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Last Checked</zh-CN>
        ///   <en>Looks up a localized string similar to: Last Checked</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_LastChecked {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_LastChecked", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Recheck</zh-CN>
        ///   <en>Looks up a localized string similar to: Recheck</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_Recheck {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_Recheck", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Health Checks</zh-CN>
        ///   <en>Looks up a localized string similar to: Health Checks</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ChecksSectionTitle {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ChecksSectionTitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Settings Registry</zh-CN>
        ///   <en>Looks up a localized string similar to: Settings Registry</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_SettingsSectionTitle {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_SettingsSectionTitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Category</zh-CN>
        ///   <en>Looks up a localized string similar to: Category</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnCategory {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnCategory", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Check</zh-CN>
        ///   <en>Looks up a localized string similar to: Check</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnCheck {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnCheck", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnStatus {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnStatus", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Summary</zh-CN>
        ///   <en>Looks up a localized string similar to: Summary</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnSummary {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnSummary", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Detail</zh-CN>
        ///   <en>Looks up a localized string similar to: Detail</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnDetail {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnDetail", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Event ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Event ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnEventId {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnEventId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Key</zh-CN>
        ///   <en>Looks up a localized string similar to: Key</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnKey {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnKey", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Name</zh-CN>
        ///   <en>Looks up a localized string similar to: Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnName {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Type</zh-CN>
        ///   <en>Looks up a localized string similar to: Type</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnType {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnType", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Current Value</zh-CN>
        ///   <en>Looks up a localized string similar to: Current Value</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnCurrentValue {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnCurrentValue", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Source</zh-CN>
        ///   <en>Looks up a localized string similar to: Source</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnSource {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnSource", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Sensitive</zh-CN>
        ///   <en>Looks up a localized string similar to: Sensitive</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnSensitive {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnSensitive", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Editable</zh-CN>
        ///   <en>Looks up a localized string similar to: Editable</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnEditable {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnEditable", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Restart</zh-CN>
        ///   <en>Looks up a localized string similar to: Restart</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnRestart {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnRestart", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Module Catalog</zh-CN>
        ///   <en>Looks up a localized string similar to: Module Catalog</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_Title {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Manage trusted deployed module packages without upload, extraction, or script loading.</zh-CN>
        ///   <en>Looks up a localized string similar to: Manage trusted deployed module packages without upload, extraction, or script loading.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_Subtitle {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Packages are discovered from deployed</zh-CN>
        ///   <en>Looks up a localized string similar to: Packages are discovered from deployed</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_DiscoveryNotePre {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_DiscoveryNotePre", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：files. This page never uploads, deletes, extracts, compiles, or loads package scripts.</zh-CN>
        ///   <en>Looks up a localized string similar to: files. This page never uploads, deletes, extracts, compiles, or loads package scripts.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_DiscoveryNotePost {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_DiscoveryNotePost", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Trusted Packages</zh-CN>
        ///   <en>Looks up a localized string similar to: Trusted Packages</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_TrustedPackagesSectionTitle {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_TrustedPackagesSectionTitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Package ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Package ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnPackageId {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnPackageId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Name</zh-CN>
        ///   <en>Looks up a localized string similar to: Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnName {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Version</zh-CN>
        ///   <en>Looks up a localized string similar to: Version</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnVersion {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnVersion", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Desktop Entry</zh-CN>
        ///   <en>Looks up a localized string similar to: Desktop Entry</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnDesktopEntry {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnDesktopEntry", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Profile</zh-CN>
        ///   <en>Looks up a localized string similar to: Profile</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnProfile {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnProfile", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：State</zh-CN>
        ///   <en>Looks up a localized string similar to: State</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnState {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnState", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Definition</zh-CN>
        ///   <en>Looks up a localized string similar to: Definition</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnDefinition {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnDefinition", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Instances</zh-CN>
        ///   <en>Looks up a localized string similar to: Instances</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnInstances {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnInstances", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Actions</zh-CN>
        ///   <en>Looks up a localized string similar to: Actions</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ColumnActions {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ColumnActions", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Register</zh-CN>
        ///   <en>Looks up a localized string similar to: Register</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ButtonRegister {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ButtonRegister", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Enable</zh-CN>
        ///   <en>Looks up a localized string similar to: Enable</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ButtonEnable {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ButtonEnable", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Disable</zh-CN>
        ///   <en>Looks up a localized string similar to: Disable</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ButtonDisable {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ButtonDisable", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Preflight</zh-CN>
        ///   <en>Looks up a localized string similar to: Preflight</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleCatalog_ButtonPreflight {
            get {
                return ResourceManager.GetString("Admin_ModuleCatalog_ButtonPreflight", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Module Type Definition</zh-CN>
        ///   <en>Looks up a localized string similar to: Module Type Definition</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_Title {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Legacy definition maintenance for trusted deployed modules.</zh-CN>
        ///   <en>Looks up a localized string similar to: Legacy definition maintenance for trusted deployed modules.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_Subtitle {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：New module definitions should be registered from verified packages in Module Catalog.</zh-CN>
        ///   <en>Looks up a localized string similar to: New module definitions should be registered from verified packages in Module Catalog.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_RegisterGuidance {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_RegisterGuidance", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Desktop and mobile source paths are read-only here to preserve the trusted deployment boundary.</zh-CN>
        ///   <en>Looks up a localized string similar to: Desktop and mobile source paths are read-only here to preserve the trusted deployment boundary.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_ReadOnlyPathsNote {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_ReadOnlyPathsNote", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Definition Metadata</zh-CN>
        ///   <en>Looks up a localized string similar to: Definition Metadata</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_MetadataSectionTitle {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_MetadataSectionTitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Friendly Name</zh-CN>
        ///   <en>Looks up a localized string similar to: Friendly Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_LabelFriendlyName {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_LabelFriendlyName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Enter a Module Name</zh-CN>
        ///   <en>Looks up a localized string similar to: Enter a Module Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_ValidationFriendlyNameRequired {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_ValidationFriendlyNameRequired", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Desktop Source</zh-CN>
        ///   <en>Looks up a localized string similar to: Desktop Source</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_LabelDesktopSource {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_LabelDesktopSource", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：You Must Enter Source Path for the Desktop Module</zh-CN>
        ///   <en>Looks up a localized string similar to: You Must Enter Source Path for the Desktop Module</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_ValidationDesktopSourceRequired {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_ValidationDesktopSourceRequired", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Desktop Source must be a relative .ascx path under DesktopModules/ or Admin/.</zh-CN>
        ///   <en>Looks up a localized string similar to: Desktop Source must be a relative .ascx path under DesktopModules/ or Admin/.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_ValidationDesktopSourcePath {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_ValidationDesktopSourcePath", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Mobile Source</zh-CN>
        ///   <en>Looks up a localized string similar to: Mobile Source</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_LabelMobileSource {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_LabelMobileSource", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Update</zh-CN>
        ///   <en>Looks up a localized string similar to: Update</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_ButtonUpdate {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_ButtonUpdate", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Cancel</zh-CN>
        ///   <en>Looks up a localized string similar to: Cancel</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_ButtonCancel {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_ButtonCancel", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Delete this module type</zh-CN>
        ///   <en>Looks up a localized string similar to: Delete this module type</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ModuleDefinitions_ButtonDelete {
            get {
                return ResourceManager.GetString("Admin_ModuleDefinitions_ButtonDelete", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Theme Settings</zh-CN>
        ///   <en>Looks up a localized string similar to: Theme Settings</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_Title {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Select trusted deployed themes for the portal and individual tabs.</zh-CN>
        ///   <en>Looks up a localized string similar to: Select trusted deployed themes for the portal and individual tabs.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_Subtitle {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Global Theme</zh-CN>
        ///   <en>Looks up a localized string similar to: Global Theme</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_GlobalThemeSectionTitle {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_GlobalThemeSectionTitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Global Theme</zh-CN>
        ///   <en>Looks up a localized string similar to: Global Theme</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_LabelGlobalTheme {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_LabelGlobalTheme", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Apply</zh-CN>
        ///   <en>Looks up a localized string similar to: Apply</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_ButtonApply {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_ButtonApply", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Reset Override</zh-CN>
        ///   <en>Looks up a localized string similar to: Reset Override</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_ButtonResetOverride {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_ButtonResetOverride", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Effective Source:</zh-CN>
        ///   <en>Looks up a localized string similar to: Effective Source:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_EffectiveSourceLabel {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_EffectiveSourceLabel", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Tab Override</zh-CN>
        ///   <en>Looks up a localized string similar to: Tab Override</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_TabOverrideSectionTitle {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_TabOverrideSectionTitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Portal Tab</zh-CN>
        ///   <en>Looks up a localized string similar to: Portal Tab</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_LabelPortalTab {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_LabelPortalTab", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Override Theme</zh-CN>
        ///   <en>Looks up a localized string similar to: Override Theme</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_LabelOverrideTheme {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_LabelOverrideTheme", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Clear Override</zh-CN>
        ///   <en>Looks up a localized string similar to: Clear Override</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_ButtonClearOverride {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_ButtonClearOverride", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Current Override:</zh-CN>
        ///   <en>Looks up a localized string similar to: Current Override:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ThemeSettings_CurrentOverrideLabel {
            get {
                return ResourceManager.GetString("Admin_ThemeSettings_CurrentOverrideLabel", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Diagnostics Logs</zh-CN>
        ///   <en>Looks up a localized string similar to: Diagnostics Logs</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_Title {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Structured runtime events for administrators.</zh-CN>
        ///   <en>Looks up a localized string similar to: Structured runtime events for administrators.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_Subtitle {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Start UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: Start UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LabelStartUtc {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LabelStartUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：End UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: End UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LabelEndUtc {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LabelEndUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Level</zh-CN>
        ///   <en>Looks up a localized string similar to: Level</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LabelLevel {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LabelLevel", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：All</zh-CN>
        ///   <en>Looks up a localized string similar to: All</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LevelAll {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LevelAll", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Info</zh-CN>
        ///   <en>Looks up a localized string similar to: Info</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LevelInfo {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LevelInfo", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Warning</zh-CN>
        ///   <en>Looks up a localized string similar to: Warning</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LevelWarning {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LevelWarning", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Error</zh-CN>
        ///   <en>Looks up a localized string similar to: Error</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LevelError {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LevelError", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Category</zh-CN>
        ///   <en>Looks up a localized string similar to: Category</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LabelCategory {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LabelCategory", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Event ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Event ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_LabelEventId {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_LabelEventId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Search</zh-CN>
        ///   <en>Looks up a localized string similar to: Search</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_ButtonSearch {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_ButtonSearch", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Previous</zh-CN>
        ///   <en>Looks up a localized string similar to: Previous</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_ButtonPrevious {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_ButtonPrevious", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Next</zh-CN>
        ///   <en>Looks up a localized string similar to: Next</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_ButtonNext {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_ButtonNext", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Log Entries</zh-CN>
        ///   <en>Looks up a localized string similar to: Log Entries</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_SectionLogEntries {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_SectionLogEntries", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_ColumnUtc {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_ColumnUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Level</zh-CN>
        ///   <en>Looks up a localized string similar to: Level</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_ColumnLevel {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_ColumnLevel", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Category</zh-CN>
        ///   <en>Looks up a localized string similar to: Category</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_ColumnCategory {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_ColumnCategory", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Message</zh-CN>
        ///   <en>Looks up a localized string similar to: Message</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_ColumnMessage {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_ColumnMessage", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Event ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Event ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticsLogs_ColumnEventId {
            get {
                return ResourceManager.GetString("Admin_DiagnosticsLogs_ColumnEventId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Operation Audits</zh-CN>
        ///   <en>Looks up a localized string similar to: Operation Audits</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_Title {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Review high-value administration and workflow changes.</zh-CN>
        ///   <en>Looks up a localized string similar to: Review high-value administration and workflow changes.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_Subtitle {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Start UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: Start UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_LabelStartUtc {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_LabelStartUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：End UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: End UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_LabelEndUtc {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_LabelEndUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Category</zh-CN>
        ///   <en>Looks up a localized string similar to: Category</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_LabelCategory {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_LabelCategory", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Action</zh-CN>
        ///   <en>Looks up a localized string similar to: Action</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_LabelAction {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_LabelAction", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Target ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Target ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_LabelTargetId {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_LabelTargetId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Search</zh-CN>
        ///   <en>Looks up a localized string similar to: Search</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ButtonSearch {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ButtonSearch", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Previous</zh-CN>
        ///   <en>Looks up a localized string similar to: Previous</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ButtonPrevious {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ButtonPrevious", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Next</zh-CN>
        ///   <en>Looks up a localized string similar to: Next</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ButtonNext {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ButtonNext", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Audit Entries</zh-CN>
        ///   <en>Looks up a localized string similar to: Audit Entries</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_SectionAuditEntries {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_SectionAuditEntries", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ColumnUtc {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ColumnUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Category</zh-CN>
        ///   <en>Looks up a localized string similar to: Category</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ColumnCategory {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ColumnCategory", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Action</zh-CN>
        ///   <en>Looks up a localized string similar to: Action</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ColumnAction {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ColumnAction", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Actor</zh-CN>
        ///   <en>Looks up a localized string similar to: Actor</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ColumnActor {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ColumnActor", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Target</zh-CN>
        ///   <en>Looks up a localized string similar to: Target</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ColumnTarget {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ColumnTarget", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Target ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Target ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ColumnTargetId {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ColumnTargetId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Summary</zh-CN>
        ///   <en>Looks up a localized string similar to: Summary</en>
        /// </lang>
        /// </summary>
        internal static string Admin_OperationAudits_ColumnSummary {
            get {
                return ResourceManager.GetString("Admin_OperationAudits_ColumnSummary", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Diagnostic Log Detail</zh-CN>
        ///   <en>Looks up a localized string similar to: Diagnostic Log Detail</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_Title {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：One structured diagnostic event.</zh-CN>
        ///   <en>Looks up a localized string similar to: One structured diagnostic event.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_Subtitle {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Back to Logs</zh-CN>
        ///   <en>Looks up a localized string similar to: Back to Logs</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_LinkBackToLogs {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_LinkBackToLogs", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Event Detail</zh-CN>
        ///   <en>Looks up a localized string similar to: Event Detail</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_SectionEventDetail {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_SectionEventDetail", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Event ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Event ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldEventId {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldEventId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldUtc {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Level</zh-CN>
        ///   <en>Looks up a localized string similar to: Level</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldLevel {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldLevel", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Category</zh-CN>
        ///   <en>Looks up a localized string similar to: Category</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldCategory {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldCategory", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Message</zh-CN>
        ///   <en>Looks up a localized string similar to: Message</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldMessage {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldMessage", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Exception Type</zh-CN>
        ///   <en>Looks up a localized string similar to: Exception Type</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldExceptionType {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldExceptionType", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Exception Detail</zh-CN>
        ///   <en>Looks up a localized string similar to: Exception Detail</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldExceptionDetail {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldExceptionDetail", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Request Path</zh-CN>
        ///   <en>Looks up a localized string similar to: Request Path</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldRequestPath {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldRequestPath", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：HTTP Method</zh-CN>
        ///   <en>Looks up a localized string similar to: HTTP Method</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldHttpMethod {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldHttpMethod", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：User Name</zh-CN>
        ///   <en>Looks up a localized string similar to: User Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldUserName {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldUserName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Client IP</zh-CN>
        ///   <en>Looks up a localized string similar to: Client IP</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldClientIp {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldClientIp", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Physical Path</zh-CN>
        ///   <en>Looks up a localized string similar to: Physical Path</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldPhysicalPath {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldPhysicalPath", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：User-Agent</zh-CN>
        ///   <en>Looks up a localized string similar to: User-Agent</en>
        /// </lang>
        /// </summary>
        internal static string Admin_DiagnosticLogDetail_FieldUserAgent {
            get {
                return ResourceManager.GetString("Admin_DiagnosticLogDetail_FieldUserAgent", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Employee Directory</zh-CN>
        ///   <en>Looks up a localized string similar to: Employee Directory</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_Title {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Read-only overview for organizations, employees, and user bindings.</zh-CN>
        ///   <en>Looks up a localized string similar to: Read-only overview for organizations, employees, and user bindings.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_Subtitle {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：System Health</zh-CN>
        ///   <en>Looks up a localized string similar to: System Health</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LinkSystemHealth {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LinkSystemHealth", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：User Administration</zh-CN>
        ///   <en>Looks up a localized string similar to: User Administration</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LinkUserAdministration {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LinkUserAdministration", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：New Organization Unit</zh-CN>
        ///   <en>Looks up a localized string similar to: New Organization Unit</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LinkNewOrganizationUnit {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LinkNewOrganizationUnit", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：New Employee</zh-CN>
        ///   <en>Looks up a localized string similar to: New Employee</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LinkNewEmployee {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LinkNewEmployee", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Bind User/Employee</zh-CN>
        ///   <en>Looks up a localized string similar to: Bind User/Employee</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LinkBindUserEmployee {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LinkBindUserEmployee", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Profile Corrections</zh-CN>
        ///   <en>Looks up a localized string similar to: Profile Corrections</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LinkProfileCorrections {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LinkProfileCorrections", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Keyword</zh-CN>
        ///   <en>Looks up a localized string similar to: Keyword</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LabelKeyword {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LabelKeyword", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Employee Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Employee Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LabelEmployeeStatus {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LabelEmployeeStatus", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Binding Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Binding Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_LabelBindingStatus {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_LabelBindingStatus", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Include inactive organization units</zh-CN>
        ///   <en>Looks up a localized string similar to: Include inactive organization units</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_CheckboxIncludeInactiveOrganizations {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_CheckboxIncludeInactiveOrganizations", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Search</zh-CN>
        ///   <en>Looks up a localized string similar to: Search</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ButtonSearch {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ButtonSearch", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Organization Units</zh-CN>
        ///   <en>Looks up a localized string similar to: Organization Units</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_SectionOrganizations {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_SectionOrganizations", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Employees</zh-CN>
        ///   <en>Looks up a localized string similar to: Employees</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_SectionEmployees {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_SectionEmployees", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Portal User Bindings</zh-CN>
        ///   <en>Looks up a localized string similar to: Portal User Bindings</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_SectionBindings {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_SectionBindings", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：ID</zh-CN>
        ///   <en>Looks up a localized string similar to: ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnId {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Code</zh-CN>
        ///   <en>Looks up a localized string similar to: Code</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnCode {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnCode", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Name</zh-CN>
        ///   <en>Looks up a localized string similar to: Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnOrgName {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnOrgName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Parent</zh-CN>
        ///   <en>Looks up a localized string similar to: Parent</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnParent {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnParent", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Sort</zh-CN>
        ///   <en>Looks up a localized string similar to: Sort</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnSort {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnSort", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Active</zh-CN>
        ///   <en>Looks up a localized string similar to: Active</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnActive {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnActive", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Action</zh-CN>
        ///   <en>Looks up a localized string similar to: Action</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnAction {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnAction", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Employee Code</zh-CN>
        ///   <en>Looks up a localized string similar to: Employee Code</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnEmployeeCode {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnEmployeeCode", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Name</zh-CN>
        ///   <en>Looks up a localized string similar to: Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnEmployeeName {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnEmployeeName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Preferred</zh-CN>
        ///   <en>Looks up a localized string similar to: Preferred</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnPreferred {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnPreferred", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Work Email</zh-CN>
        ///   <en>Looks up a localized string similar to: Work Email</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnWorkEmail {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnWorkEmail", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Organization</zh-CN>
        ///   <en>Looks up a localized string similar to: Organization</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnOrganization {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnOrganization", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnStatus {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnStatus", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Source</zh-CN>
        ///   <en>Looks up a localized string similar to: Source</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnSource {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnSource", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Binding ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Binding ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnBindingId {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnBindingId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：User ID</zh-CN>
        ///   <en>Looks up a localized string similar to: User ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnUserId {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnUserId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：User Name</zh-CN>
        ///   <en>Looks up a localized string similar to: User Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnUserName {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnUserName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Employee Name</zh-CN>
        ///   <en>Looks up a localized string similar to: Employee Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnBindingEmployeeName {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnBindingEmployeeName", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Bound UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: Bound UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnBoundUtc {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnBoundUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Reason</zh-CN>
        ///   <en>Looks up a localized string similar to: Reason</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ColumnReason {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ColumnReason", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Edit</zh-CN>
        ///   <en>Looks up a localized string similar to: Edit</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ButtonEdit {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ButtonEdit", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Bind</zh-CN>
        ///   <en>Looks up a localized string similar to: Bind</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ButtonBind {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ButtonBind", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Manage</zh-CN>
        ///   <en>Looks up a localized string similar to: Manage</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeDirectory_ButtonManage {
            get {
                return ResourceManager.GetString("Admin_EmployeeDirectory_ButtonManage", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Employee Profile Correction Requests</zh-CN>
        ///   <en>Looks up a localized string similar to: Employee Profile Correction Requests</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_Title {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_Title", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Review employee-submitted profile correction requests without directly changing master data.</zh-CN>
        ///   <en>Looks up a localized string similar to: Review employee-submitted profile correction requests without directly changing master data.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_Subtitle {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Employee Directory</zh-CN>
        ///   <en>Looks up a localized string similar to: Employee Directory</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_LinkEmployeeDirectory {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_LinkEmployeeDirectory", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Work Items</zh-CN>
        ///   <en>Looks up a localized string similar to: Work Items</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_LinkWorkItems {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_LinkWorkItems", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Operation Audits</zh-CN>
        ///   <en>Looks up a localized string similar to: Operation Audits</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_LinkOperationAudits {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_LinkOperationAudits", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_LabelStatus {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_LabelStatus", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Search</zh-CN>
        ///   <en>Looks up a localized string similar to: Search</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ButtonSearch {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ButtonSearch", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Correction Requests</zh-CN>
        ///   <en>Looks up a localized string similar to: Correction Requests</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_SectionCorrectionRequests {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_SectionCorrectionRequests", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：ID</zh-CN>
        ///   <en>Looks up a localized string similar to: ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ColumnId {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ColumnId", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Submitted UTC</zh-CN>
        ///   <en>Looks up a localized string similar to: Submitted UTC</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ColumnSubmittedUtc {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ColumnSubmittedUtc", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Employee</zh-CN>
        ///   <en>Looks up a localized string similar to: Employee</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ColumnEmployee {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ColumnEmployee", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：User</zh-CN>
        ///   <en>Looks up a localized string similar to: User</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ColumnUser {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ColumnUser", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Field</zh-CN>
        ///   <en>Looks up a localized string similar to: Field</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ColumnField {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ColumnField", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Current / Proposed</zh-CN>
        ///   <en>Looks up a localized string similar to: Current / Proposed</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ColumnCurrentProposed {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ColumnCurrentProposed", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ColumnStatus {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ColumnStatus", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Review</zh-CN>
        ///   <en>Looks up a localized string similar to: Review</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ColumnReview {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ColumnReview", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Current:</zh-CN>
        ///   <en>Looks up a localized string similar to: Current:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_LabelCurrent {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_LabelCurrent", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Proposed:</zh-CN>
        ///   <en>Looks up a localized string similar to: Proposed:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_LabelProposed {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_LabelProposed", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Note:</zh-CN>
        ///   <en>Looks up a localized string similar to: Note:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_LabelNote {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_LabelNote", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Review:</zh-CN>
        ///   <en>Looks up a localized string similar to: Review:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_LabelReview {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_LabelReview", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Approve</zh-CN>
        ///   <en>Looks up a localized string similar to: Approve</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ButtonApprove {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ButtonApprove", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Cancel</zh-CN>
        ///   <en>Looks up a localized string similar to: Cancel</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ButtonCancel {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ButtonCancel", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Reject</zh-CN>
        ///   <en>Looks up a localized string similar to: Reject</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EmployeeProfileCorrectionRequests_ButtonReject {
            get {
                return ResourceManager.GetString("Admin_EmployeeProfileCorrectionRequests_ButtonReject", resourceCulture);
            }
        }
    }
}
