//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    /// <lang>
    ///   <zh-CN>强类型资源访问器，用于查找本地化字符串等资源值。</zh-CN>
    ///   <en>Strongly typed resource accessor used to look up localized strings and related resource values.</en>
    /// </lang>
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>返回此强类型资源访问器使用的缓存 ResourceManager 实例。</zh-CN>
        ///   <en>Returns the cached ResourceManager instance used by this strongly typed resource accessor.</en>
        /// </lang>
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>重写当前线程的 CurrentUICulture，影响此强类型资源类执行的所有资源查找。</zh-CN>
        ///   <en>Overrides the current thread CurrentUICulture for all lookups performed by this strongly typed resource class.</en>
        /// </lang>
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Access Denied</zh-CN>
        ///   <en>Looks up a localized string similar to: Access Denied</en>
        /// </lang>
        /// </summary>
        internal static string Admin_AccessDenied_AccessDenied {
            get {
                return ResourceManager.GetString("Admin_AccessDenied_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Either you are not currently logged in, or you do not have access to this tab page within the portal. Please contact the portal administrator to obtain access.</zh-CN>
        ///   <en>Looks up a localized string similar to: Either you are not currently logged in, or you do not have access to this tab page within the portal. Please contact the portal administrator to obtain access.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_AccessDenied_DeniedAbout {
            get {
                return ResourceManager.GetString("Admin_AccessDenied_DeniedAbout", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Return to the ASP.NET Portal Starter Kit Home</zh-CN>
        ///   <en>Looks up a localized string similar to: Return to the ASP.NET Portal Starter Kit Home</en>
        /// </lang>
        /// </summary>
        internal static string Admin_AccessDenied_ReturnToHome {
            get {
                return ResourceManager.GetString("Admin_AccessDenied_ReturnToHome", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Edit Access Denied</zh-CN>
        ///   <en>Looks up a localized string similar to: Edit Access Denied</en>
        /// </lang>
        /// </summary>
        internal static string Admin_EditAccessDenied_EditAccessDenied {
            get {
                return ResourceManager.GetString("Admin_EditAccessDenied_EditAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Add user to this role</zh-CN>
        ///   <en>Looks up a localized string similar to: Add user to this role</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_AddUserToRole {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_AddUserToRole", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Apply Name and Password Changes</zh-CN>
        ///   <en>Looks up a localized string similar to: Apply Name and Password Changes</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_ApplyNamePwdChange {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_ApplyNamePwdChange", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Confirm Password:</zh-CN>
        ///   <en>Looks up a localized string similar to: Confirm Password:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_ConfirmPwd {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_ConfirmPwd", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Email (or Windows domain name):</zh-CN>
        ///   <en>Looks up a localized string similar to: Email (or Windows domain name):</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_Email {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_Email", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Manage User</zh-CN>
        ///   <en>Looks up a localized string similar to: Manage User</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_ManageUser {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Password:</zh-CN>
        ///   <en>Looks up a localized string similar to: Password:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_Password {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_Password", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Remove user from this role</zh-CN>
        ///   <en>Looks up a localized string similar to: Remove user from this role</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_RemoveFromRoleAlt {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_RemoveFromRoleAlt", resourceCulture);
            }
        }

        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Remove</zh-CN>
        ///   <en>Looks up a localized string similar to: Remove</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_RemoveFromRoleText {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_RemoveFromRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Save User Changes</zh-CN>
        ///   <en>Looks up a localized string similar to: Save User Changes</en>
        /// </lang>
        /// </summary>
        internal static string Admin_ManageUsers_SaveUserChange {
            get {
                return ResourceManager.GetString("Admin_ManageUsers_SaveUserChange", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Users must be registered to view secure content. Users may add themselves using the Register form, and Administrators may add users to specific roles using the Security Roles function above. This section permits Administrators to manage users and their security roles directly.</zh-CN>
        ///   <en>Looks up a localized string similar to: Users must be registered to view secure content. Users may add themselves using the Register form, and Administrators may add users to specific roles using the Security Roles function above. This section permits Administrators to manage users and their security roles directly.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_Users_FormMsg {
            get {
                return ResourceManager.GetString("Admin_Users_FormMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Domain users do not need to be registered to access portal content that is available to \"All Users\". Administrators may add domain users to specific roles using the Security Roles function above. This section permits Administrators to manage users and their security roles directly.</zh-CN>
        ///   <en>Looks up a localized string similar to: Domain users do not need to be registered to access portal content that is available to \"All Users\". Administrators may add domain users to specific roles using the Security Roles function above. This section permits Administrators to manage users and their security roles directly.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_Users_OtherMsg {
            get {
                return ResourceManager.GetString("Admin_Users_OtherMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Registered Users:</zh-CN>
        ///   <en>Looks up a localized string similar to: Registered Users:</en>
        /// </lang>
        /// </summary>
        internal static string Admin_Users_RegisteredUsers {
            get {
                return ResourceManager.GetString("Admin_Users_RegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Add New User</zh-CN>
        ///   <en>Looks up a localized string similar to: Add New User</en>
        /// </lang>
        /// </summary>
        internal static string Admin_User_AddUser {
            get {
                return ResourceManager.GetString("Admin_User_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Delete this user</zh-CN>
        ///   <en>Looks up a localized string similar to: Delete this user</en>
        /// </lang>
        /// </summary>
        internal static string Admin_User_DelUser {
            get {
                return ResourceManager.GetString("Admin_User_DelUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Edit this user</zh-CN>
        ///   <en>Looks up a localized string similar to: Edit this user</en>
        /// </lang>
        /// </summary>
        internal static string Admin_User_EditUser {
            get {
                return ResourceManager.GetString("Admin_User_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：read more...</zh-CN>
        ///   <en>Looks up a localized string similar to: read more...</en>
        /// </lang>
        /// </summary>
        internal static string Announcements_readMore {
            get {
                return ResourceManager.GetString("Announcements_readMore", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Manage Users</zh-CN>
        ///   <en>Looks up a localized string similar to: Manage Users</en>
        /// </lang>
        /// </summary>
        internal static string Module_Name_ID_32 {
            get {
                return ResourceManager.GetString("Module_Name_ID_32", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Account Login</zh-CN>
        ///   <en>Looks up a localized string similar to: Account Login</en>
        /// </lang>
        /// </summary>
        internal static string Signin_accountLogin {
            get {
                return ResourceManager.GetString("Signin_accountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Email:</zh-CN>
        ///   <en>Looks up a localized string similar to: Email:</en>
        /// </lang>
        /// </summary>
        internal static string Signin_email {
            get {
                return ResourceManager.GetString("Signin_email", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Email Or Name:</zh-CN>
        ///   <en>Looks up a localized string similar to: Email Or Name:</en>
        /// </lang>
        /// </summary>
        internal static string Signin_EmailOrName {
            get {
                return ResourceManager.GetString("Signin_EmailOrName", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Login Failed!</zh-CN>
        ///   <en>Looks up a localized string similar to: Login Failed!</en>
        /// </lang>
        /// </summary>
        internal static string Signin_LoginFaild {
            get {
                return ResourceManager.GetString("Signin_LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Password:</zh-CN>
        ///   <en>Looks up a localized string similar to: Password:</en>
        /// </lang>
        /// </summary>
        internal static string Signin_password {
            get {
                return ResourceManager.GetString("Signin_password", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Remember Login</zh-CN>
        ///   <en>Looks up a localized string similar to: Remember Login</en>
        /// </lang>
        /// </summary>
        internal static string Signin_rememberLogin {
            get {
                return ResourceManager.GetString("Signin_rememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：System Health</zh-CN>
        ///   <en>Looks up a localized string similar to: System Health</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_Title {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Runtime diagnostics and configuration registry overview.</zh-CN>
        ///   <en>Looks up a localized string similar to: Runtime diagnostics and configuration registry overview.</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_Subtitle {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Overall Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Overall Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_OverallStatus {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_OverallStatus", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Last Checked</zh-CN>
        ///   <en>Looks up a localized string similar to: Last Checked</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_LastChecked {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_LastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Recheck</zh-CN>
        ///   <en>Looks up a localized string similar to: Recheck</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_Recheck {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_Recheck", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Health Checks</zh-CN>
        ///   <en>Looks up a localized string similar to: Health Checks</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ChecksSectionTitle {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ChecksSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Settings Registry</zh-CN>
        ///   <en>Looks up a localized string similar to: Settings Registry</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_SettingsSectionTitle {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_SettingsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Category</zh-CN>
        ///   <en>Looks up a localized string similar to: Category</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnCategory {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Check</zh-CN>
        ///   <en>Looks up a localized string similar to: Check</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnCheck {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Status</zh-CN>
        ///   <en>Looks up a localized string similar to: Status</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnStatus {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Summary</zh-CN>
        ///   <en>Looks up a localized string similar to: Summary</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnSummary {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Detail</zh-CN>
        ///   <en>Looks up a localized string similar to: Detail</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnDetail {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Event ID</zh-CN>
        ///   <en>Looks up a localized string similar to: Event ID</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnEventId {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnEventId", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Key</zh-CN>
        ///   <en>Looks up a localized string similar to: Key</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnKey {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Name</zh-CN>
        ///   <en>Looks up a localized string similar to: Name</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnName {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Type</zh-CN>
        ///   <en>Looks up a localized string similar to: Type</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnType {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Current Value</zh-CN>
        ///   <en>Looks up a localized string similar to: Current Value</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnCurrentValue {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Source</zh-CN>
        ///   <en>Looks up a localized string similar to: Source</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnSource {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnSource", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Sensitive</zh-CN>
        ///   <en>Looks up a localized string similar to: Sensitive</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnSensitive {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Editable</zh-CN>
        ///   <en>Looks up a localized string similar to: Editable</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnEditable {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnEditable", resourceCulture);
            }
        }
        
        /// <summary>
        /// <lang>
        ///   <zh-CN>查找类似以下内容的本地化字符串：Restart</zh-CN>
        ///   <en>Looks up a localized string similar to: Restart</en>
        /// </lang>
        /// </summary>
        internal static string Admin_SystemHealth_ColumnRestart {
            get {
                return ResourceManager.GetString("Admin_SystemHealth_ColumnRestart", resourceCulture);
            }
        }
    }
}
