//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class MyWorkItems
    {
        /// <summary><lang><zh-CN>承载读取失败提示的面板；仅当查询失败时可见。</zh-CN><en>Panel that hosts the read-failure message; visible only when the query fails.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel FailurePanel;

        /// <summary><lang><zh-CN>显示读取失败文案的标签。</zh-CN><en>Label that displays the read-failure wording.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label FailureLabel;

        /// <summary><lang><zh-CN>承载筛选与列表的主体面板；仅当通过权限门禁后可见。</zh-CN><en>Main panel that hosts the filter and list; visible only after the permission gate passes.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel ContentPanel;

        /// <summary><lang><zh-CN>切换到"全部"筛选的链接按钮。</zh-CN><en>Link button that switches to the "all" filter.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton AllFilterButton;

        /// <summary><lang><zh-CN>切换到"仅超期"筛选的链接按钮。</zh-CN><en>Link button that switches to the "overdue only" filter.</en></lang></summary>
        protected global::System.Web.UI.WebControls.LinkButton OverdueFilterButton;

        /// <summary><lang><zh-CN>呈现待办条目的重复器。</zh-CN><en>Repeater that renders the to-do rows.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater WorkItemRepeater;

        /// <summary><lang><zh-CN>呈现空态或筛选无结果文案的面板。</zh-CN><en>Panel that renders the empty or no-match wording.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel EmptyPanel;

        /// <summary><lang><zh-CN>显示空态或筛选无结果文案的标签。</zh-CN><en>Label that displays the empty or no-match wording.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label EmptyLabel;
    }
}
