//------------------------------------------------------------------------------
// <lang>
//   <zh-CN>此文件由 Web Forms Designer 生成；手工补充的字段文档可能在重新生成后被覆盖。</zh-CN>
//   <en>This file is generated by the Web Forms Designer; manually added field documentation may be overwritten on regeneration.</en>
// </lang>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class EmployeeProfileCorrectionRequest
    {
        /// <summary><lang><zh-CN>显示资料更正请求流程的状态消息。</zh-CN><en>Displays the status message for the profile-correction request flow.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary><lang><zh-CN>承载资料展示、更正输入和请求结果的面板。</zh-CN><en>Panel that contains profile display, correction input, and request results.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Panel RequestPanel;

        /// <summary><lang><zh-CN>显示员工号的只读标签。</zh-CN><en>Read-only label that displays the employee code.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label EmployeeCodeLabel;

        /// <summary><lang><zh-CN>显示员工显示名的只读标签。</zh-CN><en>Read-only label that displays the employee display name.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label DisplayNameLabel;

        /// <summary><lang><zh-CN>显示员工偏好称呼的只读标签。</zh-CN><en>Read-only label that displays the employee preferred name.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label PreferredNameLabel;

        /// <summary><lang><zh-CN>显示员工工作邮箱的只读标签。</zh-CN><en>Read-only label that displays the employee work email.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label WorkEmailLabel;

        /// <summary><lang><zh-CN>显示员工组织名称的只读标签。</zh-CN><en>Read-only label that displays the employee organization.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Label OrganizationLabel;

        /// <summary><lang><zh-CN>选择要申请更正的资料字段。</zh-CN><en>Selects the profile field for which a correction is requested.</en></lang></summary>
        protected global::System.Web.UI.WebControls.DropDownList FieldNameList;

        /// <summary><lang><zh-CN>输入申请的资料字段建议值。</zh-CN><en>Inputs the proposed value for the requested profile field.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox ProposedValueTextBox;

        /// <summary><lang><zh-CN>输入资料更正请求备注。</zh-CN><en>Inputs the note for the profile-correction request.</en></lang></summary>
        protected global::System.Web.UI.WebControls.TextBox RequestNoteTextBox;

        /// <summary><lang><zh-CN>提交资料更正请求的按钮。</zh-CN><en>Button that submits the profile-correction request.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Button SubmitButton;

        /// <summary><lang><zh-CN>绑定当前用户近期资料更正请求的 Repeater。</zh-CN><en>Repeater bound to the current user's recent profile-correction requests.</en></lang></summary>
        protected global::System.Web.UI.WebControls.Repeater RecentRequestsRepeater;
    }
}
