//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET.StarterKit.Portal
{
    public partial class EmployeeProfileCorrectionRequest
    {
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        protected global::System.Web.UI.WebControls.Panel RequestPanel;

        protected global::System.Web.UI.WebControls.Label EmployeeCodeLabel;

        protected global::System.Web.UI.WebControls.Label DisplayNameLabel;

        protected global::System.Web.UI.WebControls.Label PreferredNameLabel;

        protected global::System.Web.UI.WebControls.Label WorkEmailLabel;

        protected global::System.Web.UI.WebControls.Label OrganizationLabel;

        protected global::System.Web.UI.WebControls.DropDownList FieldNameList;

        protected global::System.Web.UI.WebControls.TextBox ProposedValueTextBox;

        protected global::System.Web.UI.WebControls.TextBox RequestNoteTextBox;

        protected global::System.Web.UI.WebControls.Button SubmitButton;

        protected global::System.Web.UI.WebControls.Repeater RecentRequestsRepeater;
    }
}
